"""Nghĩa tiếng Việt đã biên tập cho toàn bộ mẫu ngữ pháp JLPT N1."""

MEANINGS = {
    "ni-kataku-nai": "không khó để hình dung hoặc suy ra",
    "wo-yogi-naku-sareru": "bị buộc phải / không còn lựa chọn nào khác",
    "wo-kinjienai": "không thể kìm nén một cảm xúc",
    "zu-ni-wa-okanai": "nhất định sẽ / không thể để yên mà không làm",
    "nai-dewa-okanai": "nhất định sẽ / chắc chắn dẫn đến",
    "ni-mo-mashite": "hơn cả / càng hơn nữa",
    "wo-mono-to-mo-sezu": "bất chấp / không nao núng trước",
    "ikan-ni-yorazu": "bất kể / không phụ thuộc vào (trang trọng)",
    "tomo-arou": "một người có vị thế như X mà lại...",
    "narade-wa-no": "chỉ riêng X mới có / đặc trưng độc đáo của X",
    "ni-atte": "ở / trong hoàn cảnh hoặc thời kỳ (văn viết)",
    "taru-mono-as-x": "đã là X thì phải / người mang tư cách X",
    "nari-nari": "X hay Y đều được / chẳng hạn X hoặc Y",
    "to-iwazu-to-iwazu": "dù X hay Y / khắp cả",
    "de-are-de-are": "dù là X hay Y",
    "made-da": "chỉ cần / cùng lắm thì sẽ làm",
    "made-no-koto-da": "chỉ đơn giản là đã / chẳng qua là",
    "to-wa": "thật không ngờ rằng / việc... thật là",
    "ni-itatte-wa": "riêng đến trường hợp X thì / khi nói đến X",
    "wo-oite": "ngoài X ra không có / không ai khác ngoài X",
    "koto-nashi-ni": "mà không làm / không cần làm",
    "kitte-no": "hàng đầu / nổi bật nhất trong một nhóm",
    "tomo-nareba": "khi đã trở thành / nếu ở tầm X",
    "no-itari": "vô cùng / tột độ của một cảm xúc",
    "katawara": "bên cạnh việc / đồng thời cũng",
    "gatera-while": "nhân tiện / kết hợp trong lúc làm",
    "bekarazu": "không được phép / chớ nên (lối cổ, trang trọng)",
    "zu-ni-wa-sumanai": "không thể không làm / buộc phải làm",
    "to-itta-tokoro-da": "khoảng / cùng lắm chỉ ở mức",
    "you-ni-mo-nai": "dù muốn cũng không thể",
    "n-ga-tame": "để / nhằm mục đích (văn viết)",
    "n-bakari": "như thể sắp / ra vẻ như muốn",
    "u-ni-mo": "dù định làm cũng / ngay cả khi cố làm",
    "u-mono-nara": "nếu mà dám / nếu có thể làm được",
    "tari-tomo": "dù chỉ một... cũng không",
    "nashi-ni-without": "không có / nếu thiếu X thì",
    "naku-shite-wa": "nếu không có X thì không thể",
    "ya-literary": "ngay khi / vừa... thì... (văn viết)",
    "no-kiwami": "vô cùng / đỉnh điểm của",
    "te-mae": "vì thể diện hoặc xét đến người khác nên",
    "ni-nottotte": "theo / phù hợp với quy tắc hoặc tập quán",
    "wo-motte": "bằng / với / kể từ mốc (trang trọng)",
    "tokoro-wo": "mặc dù đang / trong lúc (lời xin lỗi lịch sự)",
    "te-habakaranai": "không ngần ngại công khai tuyên bố",
    "beku-mo-nai": "không đời nào / hoàn toàn không thể",
    "to-yara": "hình như là / nghe đâu là",
    "nai-de-mo-nai": "không phải là không / không hẳn không thể",
    "wo-kawakiri-ni": "bắt đầu từ / mở đầu bằng",
    "wo-kagiri-ni": "lấy X làm lần cuối / kể từ X thì chấm dứt",
    "ori-ni": "nhân dịp / khi có dịp",
    "nagara-ni": "ngay từ khi / trong trạng thái vốn có",
    "oose-ru": "hoàn thành trọn vẹn / làm được đến cùng",
    "konasu": "thực hiện thành thạo / xử lý khéo léo",
    "mekasu": "ra vẻ / gợi vẻ hoặc sắc thái",
    "ni-hoka-naranai": "không gì khác ngoài / chính là",
    "mo-saru-koto-nagara": "X đã đành, Y còn đáng nói hơn",
    "made-mo-naku": "không cần phải / chẳng cần đến",
    "nara-mada-shimo": "nếu là X thì còn được, nhưng...",
    "nara-iza-shirazu": "nếu là X thì chưa biết, còn...",
    "hitotabi": "một khi đã / hễ một lần xảy ra",
    "to-shita-tokoro-de": "cho dù giả sử / ngay cả đối với",
    "hodo-no": "đến mức / ở mức độ",
    "zu-mogana": "không cần nói hoặc làm / tốt hơn nên để nguyên",
    "ni-matsuwaru": "liên quan đến / xoay quanh",
    "wo-kanete": "kết hợp cả / đồng thời nhằm",
    "de-ari-nagara": "mặc dù là / tuy ở tư cách",
    "te-mi-se-ru": "nhất định sẽ làm cho xem",
    "ni-shite-hajimete": "chỉ khi / phải đến X mới",
    "nagara-no": "vẫn giữ nguyên trạng thái / mang dáng vẻ truyền thống",
    "ikan-se-n": "đáng tiếc là / khó ở chỗ",
    "ni-mo-hodo-ga-aru": "cũng phải có giới hạn / quá mức chịu đựng",
    "ba-sore-made": "nếu xảy ra X thì coi như hết",
    "mo-nan-tomo-nai": "hoàn toàn không / chẳng hề",
    "ni-teihyou-ga-aru": "có tiếng / nổi tiếng về",
    "ni-tari-nai": "không đáng / không đủ tư cách để",
    "wo-mae-ni-shite": "đứng trước / đối mặt với / ngay trước thềm",
    "tari-mo-shinai": "thậm chí còn không làm",
    "ni-ari-gachi": "thường thấy ở / dễ xảy ra với",
    "sono-mono": "chính bản thân X / hiện thân của X",
    "katagata-combining": "kết hợp / đồng thời nhân tiện",
    "n-to-suru": "đang định / sắp sửa (văn viết)",
    "ni-soui-nai": "chắc chắn / không còn nghi ngờ gì",
    "yue-no": "do / bắt nguồn từ (bổ nghĩa danh từ)",
    "to-atte-wa": "nếu là trường hợp X thì",
    "ni-kakawaru": "liên quan nghiêm trọng đến / ảnh hưởng tới",
    "mono-wo-if-only": "giá mà / lẽ ra nên... nhưng",
    "to-minasu": "coi là / xem như",
    "mai-ka-wonder": "liệu có phải / chẳng phải có thể là",
    "hoka-naranu": "không ai hoặc không gì khác ngoài chính X",
    "ni-aki-tarazu": "không thỏa mãn với / chưa dừng ở",
    "beku-shite": "đúng như tất yếu / vốn đã được định là",
    "taru-yuen": "lý do khiến X là X / phẩm chất cốt lõi",
    "iyashiku-mo": "một khi đã là / nếu thực sự có tư cách",
    "n-to-bakari-ni": "như thể muốn nói / như sắp sửa",
    "sanagara": "hệt như / chẳng khác nào",
    "de-atta-to-shitemo": "ngay cả nếu đã là / giả sử đã",
    "nomi-only": "chỉ / duy nhất (văn viết)",
    "iwaba": "có thể nói là / nói ví von thì",
    "mo-kamawa-zu": "bất chấp / không màng đến",
    "ma-no-atari-ni": "tận mắt chứng kiến / đối diện trực tiếp",
    "oyoba-zu-nagara": "dù sức còn hạn chế / với tất cả khả năng nhỏ bé",
    "naku-te-nan-de-arou": "nếu không phải X thì còn là gì",
    "koto-mo-arou-ni": "không ngờ lại đúng vào / bao nhiêu thứ không chọn lại chọn",
    "ni-wa-oyoba-nai": "không cần phải / không sánh bằng",
    "ni-soku-shite": "phù hợp với / dựa sát theo",
    "to-aimatte": "kết hợp với / cộng hưởng với",
    "tara-kiri-ga-nai": "nếu kể thì không bao giờ hết",
    "ga-sai-go": "một khi... thì coi như hết / không gì ngăn được",
    "no-ue-nai": "tột bậc / không gì hơn được",
    "to-sareru": "được coi là / được cho là",
    "to-oboshii": "có vẻ là / được cho là",
    "wo-hikiai-ni": "lấy làm ví dụ / đưa ra để so sánh",
    "aro-u-koto-ka": "thật không thể tin nổi / lại còn đúng vào",
    "koso-are": "tuy có X nhưng / mặc dù X là thật",
    "aro-u-tomo": "dù có thế nào / bất kể chuyện gì xảy ra",
    "gurumi": "toàn bộ / cả tập thể cùng",
    "ikkou-ni-nai": "hoàn toàn không / mãi mà không",
    "ni-nazoraete": "ví với / mô phỏng theo",
    "nuki-de": "không có / bỏ X ra ngoài",
    "tou-no": "chính người hoặc vật đang được nói đến",
    "wo-kiwameru": "đạt đến cực điểm / tinh thông",
    "to-wa-urahara-ni": "trái với / ngược với mong đợi",
    "hiite-wa": "mở rộng ra / cuối cùng dẫn tới",
    "yoshi-mi": "vì mối quan hệ / dựa vào chỗ quen biết",
    "nagara-mo": "mặc dù / tuy vẫn đang",
    "tada-de-sae": "ngay cả bình thường đã / vốn đã",
    "ashikara-zu": "xin đừng hiểu lầm / mong thông cảm",
    "manzara-de-mo-nai": "không hẳn là không / cũng khá hài lòng",
    "desura": "ngay cả (văn viết)",
    "wo-shirime-ni": "phớt lờ / không thèm để ý",
    "koto-nagara": "đúng như thường lệ / như vốn dĩ",
    "to-nareba-if-comes-to": "nếu đến lúc / nếu rơi vào trường hợp",
    "to-naru-to-when-comes": "khi nói đến / nếu là chuyện",
    "majiki-unacceptable": "không thể chấp nhận / không xứng đáng / không được",
    "gotoku-as-if": "giống như / đúng như (văn viết)",
    "gotoki-like": "loại như / kẻ như (văn viết, thường coi nhẹ)",
    "ni-taru": "xứng đáng / đủ để",
    "ni-taeru": "chịu được / đáng để",
    "ni-taenai": "không thể chịu nổi / không đáng để",
    "te-yamanai": "không ngừng / luôn tha thiết",
    "wo-kaerimi-zu": "không màng đến / bất chấp",
    "ni-sakigakete": "đi trước / tiên phong trước",
    "to-iedomo": "mặc dù / cho dù (văn viết)",
    "to-omoi-kiya": "cứ tưởng là... nào ngờ...",
    "naritomo": "dù chỉ / ít nhất / bất cứ gì",
    "nari-as-soon-as": "ngay khi / vừa... thì... (văn viết)",
    "nari-ni-in-own-way": "theo cách riêng / phù hợp với mức của mình",
    "ga-hayai-ka": "ngay khi / vừa mới... thì... (văn viết)",
    "ni-kangamite": "xét đến / cân nhắc theo",
    "te-shikarubeki": "đáng lẽ phải / nên là như vậy",
}
