"""KanjiAI's original N2 grammar learning path.

Pattern selection is checked against Japanese Language Data (CC BY-SA 4.0).
Vietnamese explanations and example sentences are original KanjiAI content.
"""

LESSONS = [
    ("N2", "Suy đoán có căn cứ", "Phân biệt phỏng đoán dựa trên dấu hiệu, ấn tượng và tin truyền đạt.", 1),
    ("N2", "Nguyên nhân và hệ quả", "Nêu nguyên nhân khách quan, hệ quả không mong muốn và lý do trang trọng.", 2),
    ("N2", "Điều kiện và giả định", "Diễn tả giả định trái thực tế, điều kiện bắt buộc và kết quả ngoài dự tính.", 3),
    ("N2", "Mức độ và giới hạn", "Nói mức độ cực hạn, giới hạn tối thiểu và việc không thể tránh.", 4),
    ("N2", "Thời điểm và tiến trình", "Mô tả quá trình, thời điểm thay đổi và hành động ngay trước/sau một mốc.", 5),
    ("N2", "Mục đích và quan điểm", "Nêu mục đích, tiêu chí đánh giá và cách nhìn về một sự việc.", 6),
    ("N2", "So sánh và đối chiếu", "So sánh hai phía, nhấn đối lập và diễn đạt nhượng bộ.", 7),
    ("N2", "Hành động và trách nhiệm", "Nói sự chuẩn bị, nỗ lực và hành động do trách nhiệm cá nhân.", 8),
    ("N2", "Quy định và lời truyền đạt", "Diễn đạt nghĩa vụ, điều bị cấm và thông báo gián tiếp.", 9),
    ("N2", "Lập luận trong văn viết", "Liên kết luận điểm bằng các mẫu thường gặp trong tin tức và văn bản.", 10),
]

PATTERNS = [
    (1, "Plain form に 違いない", "Chắc hẳn là...; người nói có niềm tin mạnh dựa trên căn cứ.", "Mạnh hơn でしょう, nhưng vẫn là suy đoán chứ không phải sự thật đã xác minh."),
    (1, "Plain form ようだ", "Có vẻ như... dựa trên những gì người nói quan sát hay biết được.", "Dạng lịch sự là ようです; với danh từ dùng N のようだ."),
    (1, "Plain form とのことだ", "Nghe nói/được biết rằng... trong thông báo hay tin tức.", "Trang trọng hơn そうだ và thường truyền nguồn thông tin gián tiếp."),
    (2, "Plain form ため", "Vì/do... nên..., thường nêu nguyên nhân khách quan hoặc hậu quả đáng tiếc.", "Với danh từ thêm のため; tránh dùng khi muốn nêu ý chí cá nhân mạnh."),
    (2, "Plain form おかげで", "Nhờ... mà có kết quả tốt.", "Dùng おかげで cho kết quả tích cực; không hợp với kết quả xấu."),
    (2, "Plain form せいで", "Tại/vì... mà có kết quả tiêu cực.", "Mang sắc thái quy nguyên nhân hoặc than phiền, nên dùng thận trọng."),
    (3, "Vば よかった", "Giá mà đã làm...; diễn tả hối tiếc về quá khứ.", "Thường dùng với hành động lẽ ra nên thực hiện."),
    (3, "Vないことには", "Nếu không... thì không thể/không biết...", "Vế sau thường là đánh giá hoặc kết quả không thể thực hiện."),
    (3, "Vたところ", "Khi vừa thử làm A thì phát hiện/kết quả là B.", "B thường là kết quả mới biết được, không phải sự việc đã dự tính."),
    (4, "Vます-stem きれない", "Không thể làm hết vì số lượng, độ khó hay năng lực.", "Đi sau động từ có thể chia nhỏ hoặc hoàn thành đến mức nào đó."),
    (4, "Vます-stem かねない", "Có khả năng dẫn đến kết quả xấu.", "Dùng cho nguy cơ, không dùng để dự đoán điều tốt."),
    (4, "N に すぎない", "Chỉ là...; hạ thấp mức độ hay tầm quan trọng.", "Theo sau danh từ, số lượng hoặc mệnh đề ngắn."),
    (5, "Vて 以来", "Kể từ khi làm A, trạng thái B vẫn tiếp diễn.", "Mốc A thường là sự việc quan trọng đã xảy ra trong quá khứ."),
    (5, "Vます-stem つつある", "Đang dần...; mô tả quá trình thay đổi.", "Hay dùng trong văn viết với thay đổi dài hạn, không dùng cho hành động tức thời."),
    (5, "Vる ところだった", "Suýt nữa thì...; một việc gần xảy ra nhưng chưa xảy ra.", "Dùng với tình huống nguy hiểm hoặc hành động bị ngăn kịp thời."),
    (6, "V-dictionary form ように", "Làm theo cách để một mục tiêu/trạng thái được đạt tới.", "Hay đi với động từ không chủ ý như 見える・聞こえる・できる."),
    (6, "N に対して", "Đối với/nhắm tới...; chỉ đối tượng của thái độ hay hành động.", "Có thể dùng N に対する N khi bổ nghĩa cho danh từ."),
    (6, "N にとって", "Theo góc nhìn, tiêu chuẩn hoặc lợi ích của N.", "Không dùng để chỉ hướng hành động vật lý."),
    (7, "N に比べて", "So với N thì...; đặt hai đối tượng vào cùng tiêu chí.", "Có thể dùng N に比べ để nối với mệnh đề sau."),
    (7, "Plain form 一方で", "Một mặt... nhưng mặt khác...; nêu hai khía cạnh đối lập.", "Phù hợp với giải thích cân bằng trong văn nói trang trọng và văn viết."),
    (7, "Vても かまわない", "Dù làm... cũng không sao; cho phép hoặc chấp nhận.", "Trang trọng hơn てもいい, nhưng có thể nghe lạnh nếu dùng sai tình huống."),
    (8, "Vて おく", "Làm trước để chuẩn bị hoặc để giữ nguyên trạng thái cần thiết.", "N2 dùng linh hoạt hơn N4: có thể mang nghĩa để mặc/kệ cho xảy ra."),
    (8, "Vる べきだ", "Nên/phải làm vì đó là điều đúng đắn theo chuẩn mực.", "Mang tính phán xét hoặc khuyên mạnh, không nên dùng tùy tiện với người trên."),
    (8, "Vる ように 努める", "Cố gắng để hình thành hành vi hay đạt được trạng thái.", "Nhấn nỗ lực liên tục, không cam kết kết quả chắc chắn."),
    (9, "Vない わけにはいかない", "Không thể không làm vì trách nhiệm hoặc hoàn cảnh.", "Nghĩa gần với buộc phải làm, khác với không có khả năng."),
    (9, "Vては いけない", "Không được làm; nêu quy tắc hoặc điều cấm.", "Trong N2 thường xuất hiện trong cách giải thích quy định trang trọng."),
    (9, "Plain form ということだ", "Có nghĩa là/tóm lại là...; diễn giải nội dung hay kết luận.", "Dùng để giải thích hệ quả rút ra từ thông tin trước đó."),
    (10, "N を めぐって", "Xoay quanh một chủ đề/vấn đề có nhiều bên liên quan.", "Thường dùng với tranh luận, vấn đề xã hội hoặc sự kiện."),
    (10, "N に基づいて", "Dựa trên căn cứ, dữ liệu hoặc quy tắc.", "Dùng trong văn bản khách quan: dữ liệu, luật, kinh nghiệm."),
    (10, "Plain form 以上", "Vì đã/đã ở tình trạng... thì phải theo kết quả hợp lý.", "Sau mệnh đề thường là trách nhiệm hoặc quyết tâm của người nói."),
]

EXAMPLES = [
    ("Plain form に 違いない", "電気がついていますから、だれか家にいるに違いありません。", "でんきが ついていますから、だれか いえに いるに ちがいありません。", "Đèn đang bật, chắc hẳn có ai ở nhà."),
    ("Plain form ようだ", "この薬を飲めば、すぐよくなるようです。", "この くすりを のめば、すぐ よくなる ようです。", "Có vẻ uống thuốc này thì sẽ nhanh khỏe hơn."),
    ("Plain form とのことだ", "電車は事故のため遅れているとのことです。", "でんしゃは じこの ため おくれているとのことです。", "Được biết tàu đang trễ do tai nạn."),
    ("Plain form ため", "大雪のため、学校は休みになりました。", "おおゆきの ため、がっこうは やすみに なりました。", "Do tuyết lớn, trường đã nghỉ."),
    ("Plain form おかげで", "友だちが手伝ってくれたおかげで、早く終わりました。", "ともだちが てつだってくれた おかげで、はやく おわりました。", "Nhờ bạn giúp, tôi đã xong sớm."),
    ("Plain form せいで", "道が混んでいたせいで、会議に遅れました。", "みちが こんでいた せいで、かいぎに おくれました。", "Vì đường đông nên tôi đến họp muộn."),
    ("Vば よかった", "もっと早く予約すればよかったです。", "もっと はやく よやくすれば よかったです。", "Giá mà tôi đã đặt chỗ sớm hơn."),
    ("Vないことには", "実際に使ってみないことには、便利かどうかわかりません。", "じっさいに つかってみない ことには、べんりか どうか わかりません。", "Nếu chưa dùng thử thì không biết có tiện hay không."),
    ("Vたところ", "店に電話したところ、今日は休みだとわかりました。", "みせに でんわした ところ、きょうは やすみだと わかりました。", "Khi gọi cho cửa hàng, tôi mới biết hôm nay họ nghỉ."),
    ("Vます-stem きれない", "この量の仕事は一日では終わりきれません。", "この りょうの しごとは いちにちでは おわりきれません。", "Khối lượng việc này không thể hoàn tất hết trong một ngày."),
    ("Vます-stem かねない", "そんな言い方では、相手を傷つけかねません。", "そんな いいかたでは、あいてを きずつけかねません。", "Nói kiểu đó có thể làm tổn thương đối phương."),
    ("N に すぎない", "これはわたしの個人的な意見にすぎません。", "これは わたしの こじんてきな いけんに すぎません。", "Đây chỉ là ý kiến cá nhân của tôi."),
    ("Vて 以来", "日本に来て以来、毎日新しい発見があります。", "にほんに きて いらい、まいにち あたらしい はっけんが あります。", "Kể từ khi đến Nhật, mỗi ngày tôi đều có khám phá mới."),
    ("Vます-stem つつある", "町の景色は少しずつ変わりつつあります。", "まちの けしきは すこしずつ かわりつつ あります。", "Cảnh quan thành phố đang dần thay đổi."),
    ("Vる ところだった", "もう少しで階段から落ちるところでした。", "もうすこしで かいだんから おちる ところでした。", "Tôi suýt ngã từ cầu thang."),
    ("V-dictionary form ように", "忘れないように、予定をカレンダーに書きます。", "わすれない ように、よていを カレンダーに かきます。", "Để không quên, tôi viết lịch vào lịch."),
    ("N に対して", "店員は客に対して丁寧に話します。", "てんいんは きゃくに たいして ていねいに はなします。", "Nhân viên nói chuyện lịch sự với khách."),
    ("N にとって", "健康はだれにとっても大切です。", "けんこうは だれに とっても たいせつです。", "Sức khỏe quan trọng với tất cả mọi người."),
    ("N に比べて", "去年に比べて、今年は雨が多いです。", "きょねんに くらべて、ことしは あめが おおいです。", "So với năm ngoái, năm nay mưa nhiều."),
    ("Plain form 一方で", "この仕事は自由な一方で、責任も重いです。", "この しごとは じゆうな いっぽうで、せきにんも おもいです。", "Công việc này một mặt tự do nhưng mặt khác trách nhiệm cũng nặng."),
    ("Vても かまわない", "ここに荷物を置いてもかまいません。", "ここに にもつを おいても かまいません。", "Để hành lý ở đây cũng không sao."),
    ("Vて おく", "会議の資料をコピーしておきます。", "かいぎの しりょうを コピーして おきます。", "Tôi sẽ photo tài liệu cuộc họp trước."),
    ("Vる べきだ", "約束したことは守るべきです。", "やくそくした ことは まもるべきです。", "Điều đã hứa thì nên giữ."),
    ("Vる ように 努める", "野菜を毎日食べるように努めています。", "やさいを まいにち たべる ように つとめています。", "Tôi cố gắng ăn rau mỗi ngày."),
    ("Vない わけにはいかない", "明日は大事な試験なので、休むわけにはいきません。", "あしたは だいじな しけんなので、やすむ わけには いきません。", "Ngày mai có kỳ thi quan trọng nên tôi không thể không đi."),
    ("Vては いけない", "この部屋では写真を撮ってはいけません。", "この へやでは しゃしんを とっては いけません。", "Không được chụp ảnh trong phòng này."),
    ("Plain form ということだ", "来週は祝日なので、会社は休みだということです。", "らいしゅうは しゅくじつなので、かいしゃは やすみだと いうことです。", "Tuần sau là ngày lễ, nghĩa là công ty sẽ nghỉ."),
    ("N を めぐって", "新しい駅の計画をめぐって、住民が話し合っています。", "あたらしい えきの けいかくを めぐって、じゅうみんが はなしあっています。", "Người dân đang thảo luận xoay quanh kế hoạch ga mới."),
    ("N に基づいて", "この判断は調査の結果に基づいています。", "この はんだんは ちょうさの けっかに もとづいています。", "Quyết định này dựa trên kết quả khảo sát."),
    ("Plain form 以上", "約束した以上、最後まで責任を持ちます。", "やくそくした いじょう、さいごまで せきにんを もちます。", "Vì đã hứa, tôi sẽ chịu trách nhiệm đến cùng."),
]
