"""Bản Việt hóa nghĩa ngắn gọn cho toàn bộ mẫu ngữ pháp JLPT N2."""

MEANINGS = {
    "ni-atatte-occasion": "nhân dịp / vào thời điểm (trang trọng)",
    "ni-sakidatte-prior": "trước khi / trước lúc (trang trọng)",
    "wo-kikkake-ni": "lấy X làm cơ hội hoặc động lực",
    "wo-keiki-ni": "nhân cơ hội X / lấy X làm bước ngoặt (trang trọng)",
    "ni-tsuki-due-to": "vì / do; mỗi (dùng trong thông báo)",
    "yue-ni-because": "vì / do đó (văn viết)",
    "koto-kara-from-fact": "từ việc / căn cứ vào sự thật rằng",
    "amari-too-much": "vì quá... / do quá mức",
    "ba-koso-precisely-because": "chính vì... nên...",
    "kara-koso-precisely-because": "chính bởi vì... nên...",
    "ni-tomonatte-accompany": "cùng với / kéo theo / khi X tiến triển",
    "ni-oujite-depending": "tùy theo / đáp ứng / phù hợp với",
    "ni-kotaete-response": "đáp lại / đáp ứng kỳ vọng hoặc yêu cầu",
    "ni-kakawarazu-regardless": "bất kể / không phụ thuộc vào",
    "ni-mo-kakawarazu-despite": "mặc dù / bất chấp",
    "wo-towazu-regardless": "bất kể / không phân biệt",
    "wa-tomokaku": "tạm gác X sang một bên / chưa bàn đến X",
    "wa-sate-oki": "tạm gác X sang một bên (trang trọng)",
    "ni-kagitte-only": "riêng đúng lúc / cứ đúng vào trường hợp X",
    "ni-kagirazu-not-only": "không chỉ giới hạn ở X",
    "zu-ni-wa-irarenai": "không thể không / không thể kìm được",
    "nai-dewa-irarenai": "không thể không làm / không thể ngăn mình làm",
    "te-wa-irarenai": "không thể cứ tiếp tục / không có thời gian để",
    "ni-shiro-ni-seyo": "dù là... hay... / cho dù (trang trọng)",
    "toshite-mo-even-as": "ngay cả khi / giả sử rằng",
    "you-to-regardless": "dù... thế nào / bất kể",
    "you-to-mai-to": "dù có làm hay không làm",
    "mai-not-likely": "chắc sẽ không / quyết không / có lẽ không",
    "nuku-fully-do": "làm đến cùng / làm triệt để",
    "kane-nai-might": "có thể xảy ra điều không hay / có nguy cơ",
    "kane-ru-hard-to": "khó có thể / không thể chấp nhận hoặc đáp ứng",
    "dzurai-hard-emotional": "khó làm vì tâm lý hoặc cảm xúc",
    "gatai-difficult": "khó mà / khó có thể (trang trọng)",
    "beku-in-order-to": "để / nhằm mục đích (văn viết)",
    "wa-mochiron": "X thì tất nhiên, Y cũng vậy",
    "wo-tsuujite-through": "thông qua / xuyên suốt",
    "ni-wataru-span": "trải suốt / kéo dài trên một phạm vi",
    "wo-chuushin-ni-centered": "lấy X làm trung tâm / chủ yếu xoay quanh X",
    "wo-komete": "gửi gắm / đặt tình cảm hoặc ý nghĩa vào",
    "ni-shite-wa": "xét theo X thì / so với X thì",
    "ni-shite": "ở mốc X / chính là X (nhấn mạnh)",
    "sue-ni-after": "sau một quá trình dài / cuối cùng",
    "dake-no-koto-wa-aru": "quả đúng là / thật xứng với",
    "made-mo-nai": "không cần phải / không đáng để",
    "to-iu-mono-da": "đúng là / vốn là / đó mới là",
    "to-iu-mono-dewa-nai": "không hẳn cứ... là được / không đơn giản là",
    "mono-dakara": "vì / bởi vì (mang sắc thái thanh minh)",
    "yara-yara": "nào là X nào là Y (liệt kê lộn xộn)",
    "kara-shite": "xét từ / ngay từ X đã",
    "kara-suru-to": "xét từ góc độ của X / dựa vào X mà đoán",
    "kara-ni-wa": "một khi đã... thì phải...",
    "no-minarazu": "không những X mà còn Y (văn viết)",
    "to-wa-ie": "tuy nói là / mặc dù vậy",
    "to-wa-iu-mono-no": "tuy nói là... nhưng...",
    "ni-shite-mireba": "đứng trên lập trường của X mà nói",
    "kara-to-itte": "chỉ vì... mà... / tuy nói... nhưng...",
    "koto-dakara": "vì là X nên chắc hẳn / với tính cách của X",
    "te-kara-to-iu-mono": "kể từ khi... thì...",
    "tsutsu-aru": "đang dần / đang trong quá trình",
    "dake-mashi-da": "ít ra còn... / như vậy vẫn còn tốt hơn",
    "ya-inaya": "ngay khi... thì... (văn viết)",
    "ka-nai-ka-no-uchi-ni": "vừa mới... thì đã...",
    "sobakara": "vừa... xong lại... (lặp lại ngoài ý muốn)",
    "ja-arumai-shi": "đâu phải là... / vì không phải là...",
    "to-bakari-ni": "như muốn nói rằng / ra vẻ rằng",
    "to-areba": "nếu là vì / nếu đúng là trường hợp X",
    "nai-made-mo": "dù chưa đến mức... nhưng ít nhất...",
    "no-moto-de": "dưới sự chỉ đạo, điều kiện hoặc bảo trợ của",
    "sou-ni-nai": "không có vẻ / không có dấu hiệu sẽ",
    "zu-jimai": "rốt cuộc không làm được / kết thúc mà chưa làm",
    "ta-tokoro-de": "dù có... thì cũng... (kết quả không đổi)",
    "nani-shiro": "dù sao thì / bởi vì dù gì cũng",
    "nani-se": "dù sao / vấn đề là",
    "ageku-ni-end-up": "sau cùng / cuối cùng lại (kết quả không tốt)",
    "hanmen-on-other-hand": "mặt khác / đồng thời cũng",
    "kara-miru-to": "nhìn từ / xét theo quan điểm của X",
    "to-iu-koto-da": "nghe nói là / có nghĩa là",
    "kekka-result": "kết quả là / sau khi",
    "shidai-de": "tùy thuộc vào / do X quyết định",
    "ni-itaru": "đi đến / đạt tới / dẫn đến",
    "ni-itaru-made": "cho đến tận / thậm chí đến cả",
    "sai-ni": "khi / nhân dịp (trang trọng)",
    "wo-hete": "trải qua / thông qua một quá trình",
    "wo-fumaete": "dựa trên / có tính đến",
    "wo-yoso-ni": "bỏ ngoài tai / không quan tâm đến",
    "doori-just-as": "đúng như / theo như",
    "ikan-depending": "tùy theo / phụ thuộc vào (trang trọng)",
    "uru-possible": "có thể xảy ra / có khả năng",
    "to-atte": "vì ở trong hoàn cảnh đặc biệt X",
    "te-kara-denai-to": "phải sau khi... thì mới...",
    "nai-koto-niwa": "nếu không... thì không thể...",
    "to-mieru": "có vẻ là / dường như",
    "to-sureba": "giả sử / nếu đúng là vậy",
    "wa-oroka": "X còn chưa nói đến, ngay cả Y cũng...",
    "ni-suginai": "chỉ là / không hơn gì",
    "tatte-even-casual": "dù có... thì... (văn nói)",
    "koto-tote": "vì / do (cách giải thích trang trọng)",
    "atte-no-thanks-to": "chính nhờ có X mới có Y",
    "ni-terashite": "đối chiếu với / căn cứ theo",
    "kagiri-da-emotional": "vô cùng / hết sức (biểu lộ cảm xúc)",
    "kiwamari-nai": "cực kỳ / hết sức",
    "hodo-no-mono-dewa-nai": "không đến mức / không đáng để",
    "zutomo-even-without": "dù không... thì cũng...",
    "dano-dano": "nào là X nào là Y (phàn nàn hoặc chê bai)",
    "to-miru-see-as": "coi là / xem như / đánh giá là",
    "you-de-seemingly": "tưởng như... nhưng thực ra...",
    "sae-sureba-if-only": "chỉ cần / miễn là",
    "datte-casual-because": "vì... mà / nhưng... (văn nói, thanh minh)",
    "to-itte-without-particular": "không có gì đặc biệt gọi là / không hẳn là",
    "you-nara-if-looks": "nếu có vẻ sẽ / nếu tình hình là",
    "you-dewa-if-its": "nếu cứ như thế này / với tình hình này",
    "zukume-nothing-but": "toàn là / đầy những",
    "mamire-smeared": "dính đầy / phủ đầy thứ bẩn hoặc khó chịu",
    "buru-pretend": "làm ra vẻ / tỏ vẻ",
    "meku-have-look": "mang dáng vẻ / phảng phất / có vẻ",
    "mono-ga-aru": "có điểm đáng... / mang lại cảm giác mạnh",
    "to-iu-ka": "hay đúng hơn là / phải nói là",
    "to-mo-naku": "vô tình / không chủ ý",
    "kara-iu-to": "xét về / nói từ quan điểm của X",
    "naku-mo-nai": "không phải là không / cũng có thể",
    "ni-kakatte-iru": "phụ thuộc vào / đặt cả vào",
    "to-iu-no-wa": "cái gọi là / sở dĩ... là vì...",
    "hate-ni-after": "sau cùng / ở tận cùng của một quá trình",
    "sobireru-miss-chance": "lỡ mất cơ hội / không kịp làm",
    "yashinai-emphatic": "hoàn toàn không / nhất định không (nhấn mạnh, văn nói)",
    "makuru-extensively": "làm liên tục / làm rất nhiều",
    "to-iu-koto-wa": "như vậy có nghĩa là / suy ra rằng",
    "ka-to-iu-to": "nếu hỏi có phải... không thì...",
    "mono-to-shite": "coi như / giả định là",
    "te-mo-ii-kurai": "đến mức có thể / đủ để",
    "ato-wa-rest": "phần còn lại là / chỉ còn việc",
    "dake-nara": "nếu chỉ / nếu chỉ là X",
    "nai-nomi-narazu": "không những không... mà còn...",
    "tsutsu-while": "vừa... vừa... / mặc dù vẫn... (trang trọng)",
    "ni-shitagatte": "theo / cùng với sự thay đổi của X",
    "ni-sotte-along": "theo / dọc theo / phù hợp với",
    "mono-no-although": "mặc dù / tuy rằng (trang trọng)",
    "ka-no-you-ni": "như thể / cứ như là",
    "mono-nara-if-possible": "nếu có thể / nếu làm được",
    "wo-motoni-based-on": "dựa trên / lấy X làm cơ sở",
    "ue-ni-in-addition": "hơn nữa / thêm vào đó",
    "ue-wa-now": "một khi đã... thì... (trang trọng, hàm ý trách nhiệm)",
    "ijou-since": "một khi đã / vì đã... thì...",
    "shikamo-moreover": "hơn nữa / lại còn",
    "bakari-no": "chỉ còn / cứ tiếp tục theo một chiều hướng",
    "osore-ga-aru": "có nguy cơ / e rằng có thể xảy ra",
    "zaru-wo-enai": "buộc phải / không còn lựa chọn nào khác",
    "ka-to-omou-to": "vừa mới... thì đã... (thay đổi bất ngờ)",
    "hodo-dewa-nai": "không đến mức / không nhiều bằng",
}
