"""KanjiAI's original N3 grammar learning path.

Pattern selection is checked against Japanese Language Data (CC BY-SA 4.0).
Vietnamese explanations and example sentences are original KanjiAI content.
"""

LESSONS = [
    ("N3", "Nghe nói và phán đoán", "Phân biệt thông tin nghe được, vẻ bề ngoài và suy luận dựa trên dấu hiệu.", 1),
    ("N3", "Điều kiện linh hoạt", "Chọn と・ば・なら tùy quan hệ giữa điều kiện và kết quả.", 2),
    ("N3", "Mục đích và thay đổi", "Nói mục đích có chủ ý, mục tiêu và sự thay đổi khả năng.", 3),
    ("N3", "Bị động và sai khiến", "Mô tả việc bị tác động hoặc khiến người khác làm việc gì.", 4),
    ("N3", "Chuẩn bị và kết quả", "Nói việc chuẩn bị trước, kết quả còn lưu lại và việc hoàn tất.", 5),
    ("N3", "Danh từ hóa và thời điểm", "Biến mệnh đề thành danh từ và xác định thời điểm của hành động.", 6),
    ("N3", "Nhờ vả và lợi ích", "Diễn đạt hành động mang lợi ích cho ai ở mức lịch sự phù hợp.", 7),
    ("N3", "Đối lập và bổ sung", "Nối ý trái ngược, làm đồng thời và nêu nhiều lý do.", 8),
    ("N3", "Mức độ và giới hạn", "Nói quá mức, chỉ còn hoặc chỉ làm một việc.", 9),
    ("N3", "Quyết định và truyền đạt", "Nói quy định, quyết định và truyền lời khuyên/yêu cầu.", 10),
]

PATTERNS = [
    (1, "Plain form そうです", "Truyền lại thông tin nghe hoặc đọc được: nghe nói rằng...","Không dùng để phán đoán bằng mắt; trường hợp đó là Vます-stem そうです."),
    (1, "Vます-stem／い-adj そうです", "Phán đoán vẻ bề ngoài: trông có vẻ...","Với いい, đổi thành よさそうです. Không dùng mẫu này với danh từ."),
    (1, "Plain form ようです", "Suy luận cẩn trọng từ dấu hiệu hoặc thông tin có sẵn.", "ようです mềm và dè dặt hơn cách khẳng định trực tiếp."),
    (2, "V-dictionary form と", "Khi A xảy ra, B luôn hoặc thường tự động xảy ra.", "Vế sau không dùng ý chí, mệnh lệnh hay lời mời."),
    (2, "Vば", "Nếu A thì B, thường dùng cho điều kiện mang tính khái quát.", "Với động từ nhóm 1 đổi âm u thành e rồi thêm ば: 読む→読めば."),
    (2, "N／な-adj なら", "Nếu là N hoặc nếu tình huống là như vậy thì...","なら thường dựa vào thông tin người nghe vừa nêu."),
    (3, "V-dictionary form ために", "Làm A nhằm đạt một mục tiêu có chủ ý.", "Hai vế thường có cùng chủ thể và mục tiêu có thể kiểm soát."),
    (3, "V-dictionary form ように", "Làm A để đạt trạng thái hoặc khả năng khó kiểm soát trực tiếp.", "Dùng nhiều với できる, わかる, 聞こえる và thể phủ định."),
    (3, "V-dictionary form ように なります", "Nói đã trở nên có khả năng hoặc đã hình thành thói quen.", "Không nhấn vào quyết định chủ động mà nhấn vào sự thay đổi."),
    (4, "V-passive form", "Nói chủ thể bị ai đó làm một việc.", "Nhóm 1: 書く→書かれる; nhóm 2: 食べる→食べられる; する→される."),
    (4, "V-causative form", "Nói khiến hoặc cho phép ai đó làm một việc.", "Nghĩa cụ thể là ép hay cho phép phụ thuộc quan hệ và ngữ cảnh."),
    (4, "V-causative form てもらう", "Nói nhờ ai đó làm một việc theo sự cho phép/yêu cầu của mình.", "Dùng cẩn thận khi chủ thể có quyền quyết định đối với người làm."),
    (5, "Vて おきます", "Làm trước để chuẩn bị cho việc sau.", "Trong hội thoại, ておく thường rút thành とく."),
    (5, "Vて あります", "Nói kết quả của hành động có chủ ý vẫn còn ở trạng thái đó.", "Thường dùng với tha động từ: ドアが閉めてあります。"),
    (5, "Vて しまいます", "Nói đã hoàn tất hoặc lỡ làm điều không mong muốn.", "Trong hội thoại thường rút thành ちゃう／じゃう."),
    (6, "Plain form こと", "Danh từ hóa nội dung, sự việc hoặc kinh nghiệm.", "こと hợp với việc mang tính khái quát, quy tắc hay sự thật."),
    (6, "Plain form の", "Danh từ hóa một sự việc cụ thể, dễ quan sát hoặc gần gũi.", "の không thay được こと trong mọi trường hợp; xem sắc thái câu."),
    (6, "Vている ところです", "Đúng lúc đang làm một hành động.", "So với Vている, ところ nhấn vào đúng thời điểm hiện tại."),
    (7, "Vて くれます", "Nói ai đó làm điều có lợi cho người nói hoặc người thuộc phía người nói.", "Người làm là chủ ngữ, người nhận lợi ích thường không cần nêu."),
    (7, "Vて もらえませんか", "Nhờ người khác làm việc gì một cách lịch sự.", "Mềm hơn Vてください vì người nghe có thể từ chối."),
    (7, "Vて いただけますか", "Nhờ vả trang trọng với người cần tôn kính.", "Dùng được trong bối cảnh dịch vụ, công việc hoặc với cấp trên."),
    (8, "Plain form のに", "Mặc dù A nhưng kết quả B trái với điều thường mong đợi.", "Không dùng のに để đưa lời yêu cầu, mệnh lệnh hoặc ý chí ở vế sau."),
    (8, "Vます-stem ながら", "Làm A đồng thời với B.", "A là hoạt động phụ; B là hành động chính và đứng cuối câu."),
    (8, "Plain form し", "Nêu nhiều lý do hoặc nhiều đặc điểm.", "Có thể chỉ nêu một lý do bằng し khi ngụ ý còn lý do khác."),
    (9, "Vます-stem すぎます", "Nói làm quá mức hoặc một đặc điểm quá mức.", "Gắn trực tiếp vào い-adj sau khi bỏ い: 高い→高すぎる."),
    (9, "N しか Vない", "Ngoài N ra thì không có/không làm gì khác.", "Luôn đi với dạng phủ định nhưng toàn câu có nghĩa khẳng định giới hạn."),
    (9, "Vた ばかりです", "Nói vừa mới làm xong theo cảm nhận của người nói.", "Không nhất thiết là vừa xong theo thời gian chính xác."),
    (10, "V-dictionary form ことに します", "Quyết định chủ động sẽ làm gì.", "Chủ thể tự đưa ra lựa chọn; không dùng cho quy định từ bên ngoài."),
    (10, "V-dictionary form ことに なります", "Nói một quyết định, quy định hoặc thay đổi được xác định từ bên ngoài.", "Không nhấn người ra quyết định; hợp với lịch, quy tắc và tổ chức."),
    (10, "V-dictionary form ように 言います", "Truyền đạt lời nhắc, yêu cầu hoặc lời khuyên gián tiếp.", "Dùng ように với nội dung là lời chỉ dẫn, không trích dẫn nguyên văn."),
]

EXAMPLES = [
    ("Plain form そうです", "天気予報によると、あしたは暑いそうです。", "てんきよほうに よると、あしたは あついそうです。", "Theo dự báo thời tiết, nghe nói ngày mai sẽ nóng."),
    ("Vます-stem／い-adj そうです", "このケーキはおいしそうです。", "この ケーキは おいしそうです。", "Chiếc bánh này trông có vẻ ngon."),
    ("Plain form ようです", "外がぬれています。雨が降ったようです。", "そとが ぬれています。あめが ふった ようです。", "Bên ngoài ướt. Có vẻ trời đã mưa."),
    ("V-dictionary form と", "春になると、花が咲きます。", "はるに なると、はなが さきます。", "Hễ đến mùa xuân là hoa nở."),
    ("Vば", "時間があれば、手伝います。", "じかんが あれば、てつだいます。", "Nếu có thời gian, tôi sẽ giúp."),
    ("N／な-adj なら", "日本料理なら、すしが好きです。", "にほんりょうりなら、すしが すきです。", "Nếu là món Nhật thì tôi thích sushi."),
    ("V-dictionary form ために", "医者になるために、毎日勉強しています。", "いしゃに なるために、まいにち べんきょうしています。", "Để trở thành bác sĩ, tôi học mỗi ngày."),
    ("V-dictionary form ように", "漢字が読めるように、毎日練習します。", "かんじが よめる ように、まいにち れんしゅうします。", "Để có thể đọc Kanji, tôi luyện tập hằng ngày."),
    ("V-dictionary form ように なります", "日本語で新聞が読めるようになりました。", "にほんごで しんぶんが よめる ように なりました。", "Tôi đã trở nên có thể đọc báo bằng tiếng Nhật."),
    ("V-passive form", "わたしは先生にほめられました。", "わたしは せんせいに ほめられました。", "Tôi được giáo viên khen."),
    ("V-causative form", "母は子どもに野菜を食べさせます。", "ははは こどもに やさいを たべさせます。", "Mẹ bắt/cho con ăn rau."),
    ("V-causative form てもらう", "部長に早く帰らせてもらいました。", "ぶちょうに はやく かえらせて もらいました。", "Tôi đã được trưởng phòng cho phép về sớm."),
    ("Vて おきます", "旅行の前にホテルを予約しておきます。", "りょこうの まえに ホテルを よやくして おきます。", "Tôi sẽ đặt khách sạn trước chuyến đi."),
    ("Vて あります", "会議室の窓が開けてあります。", "かいぎしつの まどが あけてあります。", "Cửa sổ phòng họp đã được mở sẵn."),
    ("Vて しまいます", "電車にかばんを忘れてしまいました。", "でんしゃに かばんを わすれてしまいました。", "Tôi lỡ quên túi trên tàu."),
    ("Plain form こと", "日本で働くことはわたしの夢です。", "にほんで はたらくことは わたしの ゆめです。", "Làm việc ở Nhật là ước mơ của tôi."),
    ("Plain form の", "写真を撮るのが好きです。", "しゃしんを とるのが すきです。", "Tôi thích chụp ảnh."),
    ("Vている ところです", "今、ちょうど出かけているところです。", "いま、ちょうど でかけている ところです。", "Bây giờ tôi đang đúng lúc chuẩn bị ra ngoài."),
    ("Vて くれます", "友だちが駅まで案内してくれました。", "ともだちが えきまで あんないして くれました。", "Bạn tôi đã dẫn đường đến ga cho tôi."),
    ("Vて もらえませんか", "この書類を見てもらえませんか。", "この しょるいを みて もらえませんか。", "Bạn có thể xem giúp tôi tài liệu này không?"),
    ("Vて いただけますか", "少しゆっくり話していただけますか。", "すこし ゆっくり はなして いただけますか。", "Bạn có thể vui lòng nói chậm một chút không?"),
    ("Plain form のに", "薬を飲んだのに、まだ熱があります。", "くすりを のんだ のに、まだ ねつが あります。", "Mặc dù đã uống thuốc nhưng tôi vẫn sốt."),
    ("Vます-stem ながら", "コーヒーを飲みながら本を読みます。", "コーヒーを のみながら ほんを よみます。", "Tôi đọc sách trong khi uống cà phê."),
    ("Plain form し", "この町は静かだし、店も多いです。", "この まちは しずかだし、みせも おおいです。", "Thị trấn này vừa yên tĩnh vừa có nhiều cửa hàng."),
    ("Vます-stem すぎます", "きのうは飲みすぎました。", "きのうは のみすぎました。", "Hôm qua tôi đã uống quá nhiều."),
    ("N しか Vない", "冷蔵庫に水しかありません。", "れいぞうこに みずしか ありません。", "Trong tủ lạnh chỉ có nước."),
    ("Vた ばかりです", "さっき昼ごはんを食べたばかりです。", "さっき ひるごはんを たべた ばかりです。", "Tôi vừa mới ăn trưa xong."),
    ("V-dictionary form ことに します", "今夜は早く寝ることにします。", "こんやは はやく ねる ことに します。", "Tối nay tôi quyết định ngủ sớm."),
    ("V-dictionary form ことに なります", "来月から大阪で働くことになりました。", "らいげつから おおさかで はたらく ことに なりました。", "Từ tháng sau tôi được quyết định sẽ làm việc ở Osaka."),
    ("V-dictionary form ように 言います", "先生は学生に宿題を出すように言いました。", "せんせいは がくせいに しゅくだいを だす ように いいました。", "Giáo viên bảo học sinh hãy nộp bài tập."),
]
