"""KanjiAI's original N4 grammar learning path.

Pattern selection is checked against Japanese Language Data (CC BY-SA 4.0).
Vietnamese explanations and example sentences are original KanjiAI content.
"""

LESSONS = [
    ("N4", "Thể thông thường", "Dùng thể thông thường để nêu suy nghĩ, truyền lời và nói về sở thích.", 1),
    ("N4", "Trạng thái và thứ tự", "Diễn tả việc đang diễn ra, làm trước rồi mới làm sau, và không làm gì đó.", 2),
    ("N4", "Khả năng và trải nghiệm", "Nói điều có thể làm và kinh nghiệm đã từng có.", 3),
    ("N4", "Dự định và kế hoạch", "Nói điều dự định, lịch đã định và quyết định của bản thân.", 4),
    ("N4", "Mong muốn", "Nói mong muốn của mình và nhận biết mong muốn của người khác.", 5),
    ("N4", "Cho, nhận và nhờ giúp", "Diễn tả ai làm giúp ai và nhờ vả lịch sự.", 6),
    ("N4", "Điều kiện", "Nói điều sẽ hoặc vẫn xảy ra khi có một điều kiện.", 7),
    ("N4", "Giải thích và suy đoán", "Nêu lý do mềm mại, giải thích tình huống và dự đoán.", 8),
    ("N4", "So sánh và lựa chọn", "So sánh, chọn một phương án và nhấn điều nổi bật trong nhóm.", 9),
    ("N4", "Nối hành động nâng cao", "Liệt kê việc làm, làm đồng thời và nói điều đã xảy ra ngoài ý muốn.", 10),
]

PATTERNS = [
    (1, "Plain form と 思います", "Nói suy nghĩ hoặc ý kiến của mình.", "Với danh từ và tính từ な ở hiện tại khẳng định dùng だと思います."),
    (1, "Plain form と 言います", "Truyền lại lời nói hoặc thông tin.", "Trích dẫn nguyên câu trước と: 田中さんは来ると言いました。"),
    (1, "V-dictionary form こと", "Biến hành động thành một việc/sở thích để nói về nó.", "Ví dụ: 音楽を聞くことが好きです。"),
    (2, "Vて います", "Diễn tả hành động đang diễn ra hoặc trạng thái kéo dài.", "Một số động từ như 結婚しています thường chỉ trạng thái, không phải việc đang làm."),
    (2, "Vて から", "Làm việc A xong rồi mới làm việc B.", "Hành động trước ở thể て; hành động sau ở cuối câu."),
    (2, "Vないで", "Không làm A mà làm B, hoặc yêu cầu đừng làm A.", "Đừng nhầm với Vなくて, thường dùng để nối nguyên nhân/trạng thái."),
    (3, "V-dictionary form ことができます", "Nói có khả năng hoặc có thể thực hiện một hành động.", "Sau ことができます, động từ đứng ở thể từ điển."),
    (3, "Vた ことが あります", "Nói đã từng có trải nghiệm làm một việc.", "Không dùng để kể một lần cụ thể kèm thời điểm rõ ràng."),
    (3, "N が できます", "Nói một thứ được hoàn thành, xuất hiện hoặc có thể làm được.", "Ví dụ: 駅の前に新しいホテルができます。"),
    (4, "V-dictionary form／Vない form つもりです", "Nói dự định cá nhân sẽ hoặc không làm gì.", "つもり nhấn ý định của người nói, không phải lịch chính thức."),
    (4, "V-dictionary form 予定です", "Nói kế hoạch hoặc lịch đã được sắp xếp.", "予定 thường khách quan hơn つもり và dùng nhiều cho lịch trình."),
    (4, "V-dictionary form ようと 思っています", "Nói ý định đang cân nhắc hoặc đã ấp ủ.", "Dùng với động từ ý chí, như 行く・勉強する."),
    (5, "Vます-stem たいです", "Nói người nói muốn làm gì.", "Không dùng trực tiếp để khẳng định mong muốn của người khác."),
    (5, "Vます-stem たがっています", "Quan sát và nói người khác có vẻ muốn làm gì.", "Dựa vào biểu hiện/hành vi của người đó, không phải đọc suy nghĩ."),
    (5, "N が 欲しいです", "Nói muốn có một đồ vật hoặc điều gì đó.", "Chủ ngữ thường là người nói: わたしは新しい靴が欲しいです。"),
    (6, "Vて あげます", "Nói mình hoặc ai đó làm một việc cho người khác.", "Tránh dùng với người trên cấp vì có thể nghe như ban ơn."),
    (6, "Vて もらいます", "Nói mình nhận được sự giúp đỡ từ ai.", "Người giúp đi với に hoặc から: 先生に教えてもらいました。"),
    (6, "Vて いただけませんか", "Nhờ vả rất lịch sự: có thể vui lòng làm... không.", "Dùng khi cần lịch sự với người lạ, khách hàng hoặc cấp trên."),
    (7, "Vたら", "Nếu/sau khi A xảy ra thì B.", "Dùng được cho một điều kiện cụ thể trong tương lai."),
    (7, "Vても", "Dù A thì B vẫn đúng.", "Thể て + も: 雨が降っても行きます。"),
    (7, "N なら", "Nếu là N hoặc nếu nói về N thì...","なら thường nối với chủ đề vừa được nhắc đến trong cuộc trò chuyện."),
    (8, "Plain form ので", "Nêu nguyên nhân theo cách mềm hơn から.", "Với danh từ/tính từ な hiện tại thêm な: 静かなので。"),
    (8, "Plain form んです", "Giải thích, bổ sung bối cảnh hoặc hỏi nguyên do.", "Trong câu hỏi thường nghe: どうして遅れたんですか。"),
    (8, "Plain form でしょう", "Dự đoán hoặc xin sự đồng tình một cách nhẹ nhàng.", "Giọng lên ở cuối có thể mang nghĩa xác nhận: 寒いでしょう？"),
    (9, "N1 と N2 と どちらが adj ですか", "Hỏi trong hai lựa chọn, cái nào có đặc điểm hơn.", "Câu trả lời dùng N1/N2 のほうが adj です."),
    (9, "N の中で N が いちばん adj です", "Nêu điều nhất trong một nhóm.", "Nhóm đứng trước の中で, đối tượng nổi bật đi với が."),
    (9, "N1 は N2 より adj です", "So sánh trực tiếp: N1 ... hơn N2.", "Không dùng いちばん cùng cấu trúc so sánh hai đối tượng này."),
    (10, "Vたり Vたり します", "Nêu vài hoạt động tiêu biểu, không phải toàn bộ.", "Mỗi động từ chuyển sang thể た rồi thêm り."),
    (10, "Vます-stem ながら", "Làm A trong khi vẫn làm B.", "A là hành động phụ; hành động chính đứng ở cuối câu."),
    (10, "Vて しまいます", "Nói làm xong hoàn toàn hoặc lỡ làm điều đáng tiếc.", "Ý đáng tiếc phụ thuộc ngữ cảnh và ngữ điệu."),
]

EXAMPLES = [
    ("Plain form と 思います", "あしたは雨が降ると思います。", "あしたは あめが ふると おもいます。", "Tôi nghĩ ngày mai trời sẽ mưa."),
    ("Plain form と 言います", "田中さんは来週休むと言いました。", "たなかさんは らいしゅう やすむと いいました。", "Anh Tanaka nói tuần sau sẽ nghỉ."),
    ("V-dictionary form こと", "わたしは料理を作ることが好きです。", "わたしは りょうりを つくることが すきです。", "Tôi thích nấu ăn."),
    ("Vて います", "今、宿題をしています。", "いま、しゅくだいを しています。", "Bây giờ tôi đang làm bài tập."),
    ("Vて から", "シャワーを浴びてから寝ます。", "シャワーを あびてから ねます。", "Tôi tắm xong rồi đi ngủ."),
    ("Vないで", "朝ごはんを食べないで学校へ行きました。", "あさごはんを たべないで がっこうへ いきました。", "Tôi đã đi học mà không ăn sáng."),
    ("V-dictionary form ことができます", "わたしは少し中国語を話すことができます。", "わたしは すこし ちゅうごくごを はなすことが できます。", "Tôi có thể nói một ít tiếng Trung."),
    ("Vた ことが あります", "富士山に登ったことがあります。", "ふじさんに のぼったことが あります。", "Tôi đã từng leo núi Phú Sĩ."),
    ("N が できます", "駅の近くに新しい店ができます。", "えきの ちかくに あたらしい みせが できます。", "Một cửa hàng mới sẽ mở gần ga."),
    ("V-dictionary form／Vない form つもりです", "週末は家で休むつもりです。", "しゅうまつは いえで やすむ つもりです。", "Cuối tuần tôi định nghỉ ở nhà."),
    ("V-dictionary form 予定です", "来月大阪へ出張する予定です。", "らいげつ おおさかへ しゅっちょうする よていです。", "Tháng sau tôi dự định đi công tác Osaka."),
    ("V-dictionary form ようと 思っています", "来年日本語の試験を受けようと思っています。", "らいねん にほんごの しけんを うけようと おもっています。", "Tôi đang định năm sau thi tiếng Nhật."),
    ("Vます-stem たいです", "いつか北海道へ行きたいです。", "いつか ほっかいどうへ いきたいです。", "Một ngày nào đó tôi muốn đi Hokkaido."),
    ("Vます-stem たがっています", "妹は新しい自転車を買いたがっています。", "いもうとは あたらしい じてんしゃを かいたがっています。", "Em gái tôi có vẻ muốn mua xe đạp mới."),
    ("N が 欲しいです", "誕生日にカメラが欲しいです。", "たんじょうびに カメラが ほしいです。", "Tôi muốn có máy ảnh vào ngày sinh nhật."),
    ("Vて あげます", "わたしが荷物を持ってあげます。", "わたしが にもつを もってあげます。", "Tôi sẽ xách hành lý giúp bạn."),
    ("Vて もらいます", "友だちに駅まで送ってもらいました。", "ともだちに えきまで おくってもらいました。", "Tôi được bạn đưa đến ga."),
    ("Vて いただけませんか", "もう一度説明していただけませんか。", "もういちど せつめいして いただけませんか。", "Bạn có thể vui lòng giải thích lại một lần nữa không?"),
    ("Vたら", "時間があったら、映画を見に行きましょう。", "じかんが あったら、えいがを みに いきましょう。", "Nếu có thời gian, chúng ta đi xem phim nhé."),
    ("Vても", "忙しくても、毎日練習します。", "いそがしくても、まいにち れんしゅうします。", "Dù bận tôi vẫn luyện tập mỗi ngày."),
    ("N なら", "京都なら、秋がいちばんきれいです。", "きょうとなら、あきが いちばん きれいです。", "Nếu là Kyoto thì mùa thu đẹp nhất."),
    ("Plain form ので", "頭が痛いので、早く帰ります。", "あたまが いたいので、はやく かえります。", "Vì đau đầu nên tôi sẽ về sớm."),
    ("Plain form んです", "どうして日本語を勉強しているんですか。", "どうして にほんごを べんきょうしているんですか。", "Vì sao bạn đang học tiếng Nhật?"),
    ("Plain form でしょう", "あの店はもう閉まっているでしょう。", "あの みせは もう しまっているでしょう。", "Có lẽ cửa hàng kia đã đóng rồi."),
    ("N1 と N2 と どちらが adj ですか", "電車とバスとどちらが速いですか。", "でんしゃと バスと どちらが はやいですか。", "Tàu điện và xe buýt, cái nào nhanh hơn?"),
    ("N の中で N が いちばん adj です", "果物の中でりんごがいちばん好きです。", "くだものの なかで りんごが いちばん すきです。", "Trong các loại trái cây, tôi thích táo nhất."),
    ("N1 は N2 より adj です", "今日は昨日より暖かいです。", "きょうは きのうより あたたかいです。", "Hôm nay ấm hơn hôm qua."),
    ("Vたり Vたり します", "日曜日は本を読んだり、散歩したりします。", "にちようびは ほんを よんだり、さんぽしたり します。", "Chủ nhật tôi đọc sách, đi dạo và làm vài việc như vậy."),
    ("Vます-stem ながら", "音楽を聞きながら勉強します。", "おんがくを ききながら べんきょうします。", "Tôi học trong khi nghe nhạc."),
    ("Vて しまいます", "宿題を忘れてしまいました。", "しゅくだいを わすれてしまいました。", "Tôi lỡ quên bài tập rồi."),
]
