"""KanjiAI's original N5 grammar learning path.

The pattern inventory was checked against Japanese Language Data (CC BY-SA 4.0)
and arranged as short, practical lessons inspired by the topic-first navigation
seen in Nhai Kanji. Vietnamese explanations and examples below are original.
"""

LESSONS = [
    ("N5", "Chào hỏi và giới thiệu", "Dùng です để giới thiệu, phủ định và đặt câu hỏi lịch sự.", 1),
    ("N5", "Chỉ định và sở hữu", "Gọi đúng người, đồ vật và nói vật đó thuộc về ai.", 2),
    ("N5", "Trợ từ trong hành động", "Nói làm gì, ở đâu và cùng ai bằng を・で・と.", 3),
    ("N5", "Nơi chốn và sự tồn tại", "Mô tả người hoặc vật ở đâu bằng あります・います.", 4),
    ("N5", "Động từ lịch sự", "Nói việc hiện tại, quá khứ và phủ định bằng các dạng ます.", 5),
    ("N5", "Thời gian và di chuyển", "Nói giờ giấc, điểm đến và khoảng thời gian.", 6),
    ("N5", "Tính từ cơ bản", "Miêu tả đồ vật, nơi chốn và trạng thái bằng tính từ い・な.", 7),
    ("N5", "Sở thích và mong muốn", "Nói điều mình thích, giỏi và muốn làm.", 8),
    ("N5", "Nhờ vả và cho phép", "Yêu cầu, xin phép và diễn đạt điều không được làm.", 9),
    ("N5", "Nối ý và so sánh", "Nối hành động, nêu lý do và so sánh hai sự vật.", 10),
]

PATTERNS = [
    (1, "N は N です", "Nói A là B theo lối lịch sự.", "は đọc là wa khi làm trợ từ; đặt sau chủ đề đang nói tới."),
    (1, "N は N じゃありません", "Phủ định lịch sự: A không phải là B.", "Trong văn viết trang trọng có thể gặp ではありません."),
    (1, "N は N ですか", "Hỏi A có phải là B không.", "Tiếng Nhật không đảo trật tự từ; thêm か ở cuối để tạo câu hỏi."),
    (2, "これ・それ・あれ は N です", "Chỉ một vật: này, đó gần người nghe, hoặc kia xa cả hai.", "Dùng riêng được, không đặt trực tiếp trước danh từ."),
    (2, "この・その・あの N", "Chỉ danh từ: N này, N đó, N kia.", "Phải theo ngay trước danh từ, ví dụ この本."),
    (2, "N1 の N2", "N2 của N1 hoặc N2 có liên hệ với N1.", "の không chỉ sở hữu: 日本の会社 là công ty ở/thuộc Nhật Bản."),
    (3, "N を Vます", "Đánh dấu đối tượng trực tiếp của hành động.", "を đọc là o; dùng với ăn, uống, đọc, xem, mua..."),
    (3, "Place で Vます", "Nói nơi diễn ra hành động.", "Dùng で với nơi làm hành động, khác với に chỉ nơi tồn tại."),
    (3, "N と Vます", "Nói làm một việc cùng ai hoặc làm các danh từ cùng nhau.", "Khi chỉ cùng với ai, đặt người đó trước と."),
    (4, "Place に N が あります", "Có vật, cây cối hoặc sự vật vô tri ở một nơi.", "Không dùng あります cho người và động vật."),
    (4, "Place に N が います", "Có người hoặc động vật ở một nơi.", "います cũng dùng cho sinh vật như mèo, chim, cá."),
    (4, "N は Place に あります・います", "Đưa vật/người lên làm chủ đề rồi nói vị trí của nó.", "Chọn あります hay います theo tính chất của N."),
    (5, "Vます", "Dạng hiện tại/tương lai lịch sự của động từ.", "Tùy ngữ cảnh, 食べます có thể là ăn hoặc sẽ ăn."),
    (5, "Vません", "Phủ định lịch sự ở hiện tại/tương lai.", "Đi với từ thời gian để làm rõ: あした行きません。"),
    (5, "Vました", "Kể một hành động đã hoàn thành trong quá khứ.", "Đổi ます thành ました, ví dụ 見ます → 見ました."),
    (6, "Time に Vます", "Nêu thời điểm cụ thể diễn ra hành động.", "Thường không dùng に với 今日, 明日, 毎日."),
    (6, "Place へ・に 行きます／来ます／帰ります", "Nói nơi đến, đến đây hoặc trở về.", "へ nhấn hướng đi; に nhấn điểm đến. Cả hai đều dùng được trong mẫu này."),
    (6, "Time から Time まで", "Nói từ mốc bắt đầu đến mốc kết thúc.", "Có thể dùng riêng một vế nếu chỉ biết thời điểm bắt đầu hoặc kết thúc."),
    (7, "N は い-adj です", "Miêu tả bằng tính từ kết thúc bằng い.", "Không thêm な trước danh từ với nhóm này: おいしい料理."),
    (7, "N は な-adj です", "Miêu tả bằng tính từ な như しずか・きれい・ゆうめい.", "Khi đứng trước danh từ, thêm な: しずかな町."),
    (7, "い-adj くないです／な-adj じゃありません", "Phủ định tính từ một cách lịch sự.", "Ví dụ 高くないです và しずかじゃありません."),
    (8, "N が 好きです・嫌いです", "Nói thích hoặc không thích một thứ.", "Mẫu cơ bản dùng が, không dùng を cho 好きです."),
    (8, "N が 上手です・下手です", "Nói ai đó giỏi hoặc chưa giỏi một kỹ năng.", "Dùng với kỹ năng: 日本語が上手です。"),
    (8, "Vます-stem たいです", "Nói mong muốn tự mình làm một việc.", "Bỏ ます rồi thêm たいです: 行きます → 行きたいです。"),
    (9, "Vてください", "Lịch sự nhờ hoặc yêu cầu người nghe làm việc gì.", "Dùng với người nghe; tránh dùng để nói về hành động của chính mình."),
    (9, "Vてもいいです", "Xin hoặc cho phép làm một việc.", "Câu hỏi tự nhiên: 写真を撮ってもいいですか。"),
    (9, "Vてはいけません", "Nói điều bị cấm hoặc không được phép.", "Trong giao tiếp thân mật có thể nghe ちゃいけません."),
    (10, "Vて、Vます", "Nối các hành động theo thứ tự hoặc liệt kê hành động.", "Không dùng thể て để diễn tả hai ý đối lập; khi đó dùng でも hoặc が."),
    (10, "Sentence から、Sentence", "Nêu lý do rồi kết quả: vì... nên....", "から đứng sau lý do; có thể đặt lý do sau câu trong hội thoại."),
    (10, "A は B より adj です", "So sánh: A ... hơn B.", "B đứng trước より; tính từ ở cuối câu."),
]

EXAMPLES = [
    ("N は N です", "わたしは学生です。", "わたしは がくせいです。", "Tôi là học sinh/sinh viên."),
    ("N は N じゃありません", "田中さんは先生じゃありません。", "たなかさんは せんせいじゃありません。", "Anh Tanaka không phải là giáo viên."),
    ("N は N ですか", "ミラーさんは会社員ですか。", "ミラーさんは かいしゃいんですか。", "Anh Miller có phải là nhân viên công ty không?"),
    ("これ・それ・あれ は N です", "これは日本語の本です。", "これは にほんごの ほんです。", "Đây là sách tiếng Nhật."),
    ("この・その・あの N", "そのかばんはだれのですか。", "その かばんは だれのですか。", "Cái túi đó là của ai?"),
    ("N1 の N2", "これはわたしの辞書です。", "これは わたしの じしょです。", "Đây là từ điển của tôi."),
    ("N を Vます", "毎朝コーヒーを飲みます。", "まいあさ コーヒーを のみます。", "Mỗi sáng tôi uống cà phê."),
    ("Place で Vます", "図書館で本を読みます。", "としょかんで ほんを よみます。", "Tôi đọc sách ở thư viện."),
    ("N と Vます", "友だちと映画を見ます。", "ともだちと えいがを みます。", "Tôi xem phim cùng bạn."),
    ("Place に N が あります", "机の上に本があります。", "つくえの うえに ほんが あります。", "Có một quyển sách trên bàn."),
    ("Place に N が います", "公園に犬がいます。", "こうえんに いぬが います。", "Có một con chó ở công viên."),
    ("N は Place に あります・います", "郵便局は駅の前にあります。", "ゆうびんきょくは えきの まえに あります。", "Bưu điện ở trước ga."),
    ("Vます", "毎日日本語を勉強します。", "まいにち にほんごを べんきょうします。", "Tôi học tiếng Nhật mỗi ngày."),
    ("Vません", "日曜日は学校へ行きません。", "にちようびは がっこうへ いきません。", "Chủ nhật tôi không đi học."),
    ("Vました", "きのう友だちに会いました。", "きのう ともだちに あいました。", "Hôm qua tôi đã gặp bạn."),
    ("Time に Vます", "七時に起きます。", "しちじに おきます。", "Tôi thức dậy lúc bảy giờ."),
    ("Place へ・に 行きます／来ます／帰ります", "来週京都へ行きます。", "らいしゅう きょうとへ いきます。", "Tuần sau tôi đi Kyoto."),
    ("Time から Time まで", "銀行は九時から三時までです。", "ぎんこうは くじから さんじまでです。", "Ngân hàng mở từ chín giờ đến ba giờ."),
    ("N は い-adj です", "このりんごは赤いです。", "この りんごは あかいです。", "Quả táo này đỏ."),
    ("N は な-adj です", "この町はしずかです。", "この まちは しずかです。", "Thị trấn này yên tĩnh."),
    ("い-adj くないです／な-adj じゃありません", "今日は寒くないです。", "きょうは さむくないです。", "Hôm nay không lạnh."),
    ("N が 好きです・嫌いです", "わたしは音楽が好きです。", "わたしは おんがくが すきです。", "Tôi thích âm nhạc."),
    ("N が 上手です・下手です", "山田さんは料理が上手です。", "やまださんは りょうりが じょうずです。", "Chị Yamada nấu ăn giỏi."),
    ("Vます-stem たいです", "日本へ行きたいです。", "にほんへ いきたいです。", "Tôi muốn đi Nhật Bản."),
    ("Vてください", "ここに名前を書いてください。", "ここに なまえを かいてください。", "Hãy viết tên vào đây."),
    ("Vてもいいです", "ここで写真を撮ってもいいですか。", "ここで しゃしんを とっても いいですか。", "Tôi có thể chụp ảnh ở đây không?"),
    ("Vてはいけません", "ここでタバコを吸ってはいけません。", "ここで タバコを すっては いけません。", "Không được hút thuốc ở đây."),
    ("Vて、Vます", "朝ごはんを食べて、学校へ行きます。", "あさごはんを たべて、がっこうへ いきます。", "Tôi ăn sáng rồi đi học."),
    ("Sentence から、Sentence", "時間がありませんから、タクシーで行きます。", "じかんが ありませんから、タクシーで いきます。", "Vì không có thời gian nên tôi đi taxi."),
    ("A は B より adj です", "電車はバスより速いです。", "でんしゃは バスより はやいです。", "Tàu điện nhanh hơn xe buýt."),
]
