import React, { useEffect, useRef, useState } from 'react';
import { BrowserRouter, useLocation, useNavigate } from 'react-router-dom';
import { createRoot } from 'react-dom/client';
import './styles.css';

let KANJI = [];
const nav = [['home','⌂','Trang chủ'],['learn','◈','Học Kanji'],['vocabulary','▤','Từ vựng'],['grammar','文','Ngữ pháp'],['review','↻','Ôn tập']];
const KANJIVG_FILES = { '日':'065e5','人':'04eba','学':'05b66','食':'098df','水':'06c34','本':'0672c','会':'04f1a','山':'05c71','木':'06728','書':'066f8' };

function StrokeOrder({char}) {
  const host = useRef(null), [svg,setSvg] = useState(''), code = KANJIVG_FILES[char];
  useEffect(()=>{let active=true; setSvg(''); if(!code)return; fetch(`/kanjivg/${code}.svg`).then(r=>r.ok?r.text():Promise.reject()).then(markup=>active&&setSvg(markup.replace(/^<\?xml[\s\S]*?\?>/,'').replace(/<!--[\s\S]*?-->/g,'').replace(/<!DOCTYPE[\s\S]*?\]>\s*/,''))).catch(()=>active&&setSvg('')); return ()=>{active=false}},[code]);
  useEffect(()=>{if(!svg||!host.current)return; host.current.querySelectorAll('path').forEach(path=>{path.style.strokeDasharray='none';path.style.strokeDashoffset='0'});},[svg]);
  if(!code) return <div className="kanjivg-board fallback"><b>{char}</b><small>SVG nét viết đang được bổ sung</small></div>;
  return <div className="kanjivg-board" ref={host} aria-label={`Thứ tự nét chữ ${char}`}>{svg?<div dangerouslySetInnerHTML={{__html:svg}}/>:<span>Đang tải nét viết…</span>}</div>
}

function WritingCanvas({onRecognize}) {
  const canvasRef = useRef(null), guideRef=useRef(null), isDrawing=useRef(false), timer=useRef(), lastPoint=useRef(null), lastMidpoint=useRef(null), strokeCount=useRef(0), history=useRef([]);
  const [hasInk,setHasInk]=useState(false),[canUndo,setCanUndo]=useState(false);
  const drawGuide=()=>{const c=guideRef.current;if(!c)return;const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#d9d3c6';ctx.lineWidth=Math.max(1,window.devicePixelRatio||1);ctx.setLineDash([6*(window.devicePixelRatio||1),8*(window.devicePixelRatio||1)]);ctx.beginPath();ctx.moveTo(w/2,0);ctx.lineTo(w/2,h);ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke()};
  useEffect(()=>{const ink=canvasRef.current,guide=guideRef.current;const resize=()=>{const r=ink.getBoundingClientRect(),scale=Math.min(window.devicePixelRatio||1,3),size=Math.max(1,Math.round(Math.min(r.width||400,r.height||400)*scale));ink.width=ink.height=size;guide.width=guide.height=size;drawGuide()};const observer=new ResizeObserver(resize);observer.observe(ink);resize();return()=>{observer.disconnect();clearTimeout(timer.current)}},[]);
  const position=(e)=>{const r=canvasRef.current.getBoundingClientRect(),p=e;return {x:(p.clientX-r.left)*canvasRef.current.width/r.width,y:(p.clientY-r.top)*canvasRef.current.height/r.height,pressure:p.pointerType==='pen'&&p.pressure>0?p.pressure:.5}};
  const inkPoint=(p,first=false)=>{const ctx=canvasRef.current.getContext('2d'),previous=lastPoint.current,base=Math.max(7,canvasRef.current.width/30),width=base*(.72+p.pressure*.56);ctx.strokeStyle='#2446be';ctx.fillStyle='#2446be';ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=width;if(first||!previous){ctx.beginPath();ctx.arc(p.x,p.y,width/2,0,Math.PI*2);ctx.fill();lastMidpoint.current=p}else{const middle={x:(previous.x+p.x)/2,y:(previous.y+p.y)/2},from=lastMidpoint.current||previous;ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.quadraticCurveTo(previous.x,previous.y,middle.x,middle.y);ctx.stroke();lastMidpoint.current=middle}lastPoint.current=p};
  const begin=(e)=>{e.preventDefault();clearTimeout(timer.current);const canvas=canvasRef.current,ctx=canvas.getContext('2d');history.current.push({image:ctx.getImageData(0,0,canvas.width,canvas.height),strokes:strokeCount.current});if(history.current.length>20)history.current.shift();setCanUndo(true);isDrawing.current=true;strokeCount.current+=1;canvas.setPointerCapture?.(e.pointerId);const p=position(e);inkPoint(p,true);setHasInk(true)};
  const draw=(e)=>{if(!isDrawing.current)return;e.preventDefault();const events=e.getCoalescedEvents?.()||[e];events.forEach(point=>inkPoint(position(point)))};
  const imageForRecognition=()=>{const source=canvasRef.current,output=document.createElement('canvas');output.width=source.width;output.height=source.height;const ctx=output.getContext('2d');ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,output.width,output.height);ctx.drawImage(source,0,0);return output.toDataURL('image/png')};
  const end=(e)=>{if(!isDrawing.current)return;isDrawing.current=false;lastPoint.current=null;lastMidpoint.current=null;canvasRef.current.releasePointerCapture?.(e?.pointerId);clearTimeout(timer.current);timer.current=setTimeout(()=>onRecognize(imageForRecognition(),strokeCount.current),450)};
  const clear=()=>{const c=canvasRef.current;c.getContext('2d').clearRect(0,0,c.width,c.height);lastPoint.current=null;lastMidpoint.current=null;strokeCount.current=0;history.current=[];clearTimeout(timer.current);setHasInk(false);setCanUndo(false)};
  const undo=()=>{const previous=history.current.pop();if(!previous)return;const c=canvasRef.current;c.getContext('2d').putImageData(previous.image,0,0);strokeCount.current=previous.strokes;lastPoint.current=null;lastMidpoint.current=null;clearTimeout(timer.current);setHasInk(previous.strokes>0);setCanUndo(history.current.length>0)};
  const search=()=>{if(hasInk){clearTimeout(timer.current);onRecognize(imageForRecognition(),strokeCount.current)}};
  return <div className="canvas-wrap"><p className="canvas-title">Viết một Kanji</p><div className="canvas-stage"><canvas ref={guideRef} className="guide-layer" aria-hidden="true"/><canvas ref={canvasRef} className="ink-layer" onPointerDown={begin} onPointerMove={draw} onPointerUp={end} onPointerCancel={end}/></div><div className="canvas-controls"><button onClick={undo} disabled={!canUndo} aria-label="Hoàn tác nét vừa viết">↶</button><button onClick={clear} disabled={!hasInk} aria-label="Xóa toàn bộ nét vẽ">♲</button><button className="canvas-search" onClick={search} disabled={!hasInk} aria-label="Nhận diện Kanji">⌕</button></div></div>
}

function FlashcardWritingPad({expectedText}){
 const canvasRef=useRef(null),drawing=useRef(false),[hasInk,setHasInk]=useState(false),[saveState,setSaveState]=useState('');
 const drawGuide=c=>{const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.strokeStyle='#8fa1bd';ctx.lineWidth=1.5;ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(0,c.height/2);ctx.lineTo(c.width,c.height/2);ctx.stroke();ctx.beginPath();ctx.moveTo(c.width/2,0);ctx.lineTo(c.width/2,c.height);ctx.stroke();ctx.restore()};
 useEffect(()=>{drawGuide(canvasRef.current)},[]);
 const point=e=>{const r=canvasRef.current.getBoundingClientRect();return{x:(e.clientX-r.left)*canvasRef.current.width/r.width,y:(e.clientY-r.top)*canvasRef.current.height/r.height}};
 const start=e=>{e.stopPropagation();drawing.current=true;canvasRef.current.setPointerCapture?.(e.pointerId);const p=point(e),ctx=canvasRef.current.getContext('2d');ctx.setLineDash([]);ctx.strokeStyle='#f1f7ed';ctx.lineWidth=6;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(p.x,p.y)};
 const draw=e=>{if(!drawing.current)return;e.stopPropagation();const p=point(e);canvasRef.current.getContext('2d').lineTo(p.x,p.y);canvasRef.current.getContext('2d').stroke();setHasInk(true)};
 const clear=e=>{e.stopPropagation();drawGuide(canvasRef.current);setHasInk(false);setSaveState('')};
 const saveSample=async e=>{e.stopPropagation();if(!hasInk)return;setSaveState('Đang lưu…');try{const response=await fetch('http://localhost:8010/api/handwriting/samples',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:canvasRef.current.toDataURL('image/png'),expected_text:expectedText,source:'flashcard'})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Không thể lưu');setSaveState(data.message)}catch(error){setSaveState(error.message||'Không kết nối được backend')}};
 return <div className="flash-writing" onClick={e=>e.stopPropagation()}><div><span>LUYỆN VIẾT · {expectedText}</span><small>Thu thập mẫu cho AI</small><button onClick={clear} disabled={!hasInk}>↺ Xóa</button></div><canvas ref={canvasRef} width="330" height="120" onPointerDown={start} onPointerMove={draw} onPointerUp={()=>drawing.current=false} onPointerLeave={()=>drawing.current=false}/><div className="writing-actions"><button onClick={saveSample} disabled={!hasInk}>Lưu mẫu viết</button>{saveState&&<small>{saveState}</small>}</div></div>
}

function App(){
 const location=useLocation(),navigate=useNavigate();
 const [selected,setSelected]=useState(null),[query,setQuery]=useState(''),[results,setResults]=useState([]),[recognitionNote,setRecognitionNote]=useState(''),[dark,setDark]=useState(false),[toast,setToast]=useState(''),[kanjiVersion,setKanjiVersion]=useState(0),recognitionRequest=useRef(0);
 useEffect(()=>{fetch('http://localhost:8010/kanji?level=N5').then(r=>r.ok?r.json():[]).then(data=>{KANJI=data.map(x=>({...x,on:x.on_reading,kun:x.kun_reading,words:[]}));setKanjiVersion(v=>v+1)}).catch(()=>{KANJI=[];setKanjiVersion(v=>v+1)})},[]);
 const notify=(text)=>{setToast(text);setTimeout(()=>setToast(''),2400)};
 const recognition=async(img,strokeCount)=>{const requestId=++recognitionRequest.current;setResults([]);setRecognitionNote('Đang kiểm tra nét viết…');try{let r=await fetch('http://localhost:8010/api/recognition',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:img,stroke_count:strokeCount})});let d=await r.json();if(requestId!==recognitionRequest.current)return;if(!r.ok)throw new Error(d.detail||'Không thể nhận diện');setResults(d.predictions||[]);setRecognitionNote(d.uncertain?'Kết quả chưa chắc — hãy viết rõ hơn hoặc thử lại.':(d.message||''))}catch(error){if(requestId===recognitionRequest.current)setRecognitionNote(error.message||'Không kết nối được backend')}};
 const path=location.pathname, lessonMatch=path.match(/^\/vocabulary\/n5\/lesson\/(\d+)(\/flashcard)?$/), grammarMatch=path.match(/^\/grammar\/n5\/lesson\/(\d+)$/), page=path.startsWith('/kanji/')?'detail':path.startsWith('/vocabulary')?'vocabulary':path.startsWith('/grammar')?'grammar':path.startsWith('/learn')?'learn':path.startsWith('/review')?'review':path.startsWith('/settings')?'settings':path.startsWith('/login')?'login':'home';
 useEffect(()=>{if(page==='detail'){const char=decodeURIComponent(path.split('/').pop());setSelected(KANJI.find(x=>x.char===char)||null)}},[path,page,kanjiVersion]);
 const go=(to)=>{navigate(to);window.scrollTo(0,0)};
 const openKanji=(k)=>{setSelected(k);go(`/kanji/${encodeURIComponent(k.char)}`)};
 const matches=KANJI.filter(k=>`${k.char} ${k.meaning} ${k.on} ${k.kun}`.toLowerCase().includes(query.toLowerCase()));
 return <div className={dark?'app dark':'app'}>
  <aside><div className="brand"><div className="logo">漢</div><div><b>Kanji<span>AI</span></b><small>Học chữ Nhật mỗi ngày</small></div></div><nav>{nav.map(([id,ic,label])=><button key={id} className={page===id?'active':''} onClick={()=>go(id==='home'?'/':id==='learn'?'/learn/kanji':id==='grammar'?'/grammar/n5':`/${id}`)}><i>{ic}</i>{label}</button>)}</nav><div className="sidebar-bottom"><button onClick={()=>go('/settings')}><i>⚙</i>Cài đặt</button><button onClick={()=>go('/login')}><i>◉</i>Đăng nhập</button></div></aside>
  <main><header><div className="crumb">{page==='home'?'Khám phá':page==='detail'?'Kanji / '+selected?.char:'Học tiếng Nhật'}</div><div className="head-actions"><button className="theme" onClick={()=>setDark(!dark)}>{dark?'☀':'☾'}</button><div className="avatar">H</div></div></header>
  {page==='home'&&<Home query={query} setQuery={setQuery} matches={matches} openKanji={openKanji} results={results} recognition={recognition} recognitionNote={recognitionNote}/>} 
  {page==='detail'&&selected&&<Detail item={selected} back={()=>go('/')} notify={notify}/>} 
  {page==='learn'&&<Learn openKanji={openKanji}/>} {page==='vocabulary'&&(!lessonMatch?<Vocabulary go={go}/>:lessonMatch[2]?<Flashcards lessonId={lessonMatch[1]} go={go}/>:<LessonDetail lessonId={lessonMatch[1]} go={go}/>)} {page==='grammar'&&(!grammarMatch?<GrammarList go={go}/>:<GrammarLesson lessonId={grammarMatch[1]} go={go}/>)} {page==='review'&&<Review openKanji={openKanji}/>} {page==='settings'&&<Settings dark={dark} setDark={setDark} notify={notify}/>} {page==='login'&&<Login notify={notify}/>} 
  </main>{toast&&<div className="toast">✓ {toast}</div>}</div>
}

function Home({query,setQuery,matches,openKanji,results,recognition,recognitionNote}){return <section className="home"><div className="hero"><div><p className="eyebrow">KANJI AI · BẮT ĐẦU HÔM NAY</p><h1>Viết một nét,<br/><em>nhớ một đời.</em></h1><p className="intro">Khám phá Kanji theo cách trực quan hơn — tra cứu, luyện viết và học mỗi ngày.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm Kanji, âm Hán Việt hoặc ý nghĩa..."/>{query&&<div className="suggestions">{matches.map(k=><button key={k.char} onClick={()=>openKanji(k)}><b>{k.char}</b><span>{k.meaning}</span></button>)||<p>Không tìm thấy kết quả</p>}</div>}</div></div><div className="hero-mark">学<small>まなぶ</small></div></div>
<div className="two-col"><section className="panel writing"><div className="panel-title"><div><p className="eyebrow">AI HANDWRITING</p><h2>Viết Kanji để tra cứu</h2></div><span className="live"><i/> AI sẵn sàng</span></div><p className="hint">Viết một ký tự Nhật vào ô bên dưới. AI sẽ đưa ra các kết quả gần nhất khi bạn dừng bút.</p><div className="write-grid"><WritingCanvas onRecognize={recognition}/><div className="prediction"><p className="prediction-label">{results.length?'KẾT QUẢ NHẬN DIỆN':'TRẠNG THÁI AI'}</p>{results.length?<>{results.map((r,i)=><div className="pred" key={r.kanji}><b>{r.kanji}</b><div><div className="bar"><i style={{width:`${r.confidence*100}%`}}/></div><small>Độ tin cậy {Math.round(r.confidence*100)}%</small></div>{i===0&&r.confidence>=.6&&<span>Khả năng cao</span>}{i===0&&r.confidence<.6&&<span>Chưa chắc</span>}</div>)}{recognitionNote&&<p className="hint">{recognitionNote}</p>}<button className="link-button" onClick={()=>openKanji(KANJI.find(k=>k.char===results[0].kanji)||KANJI[3])}>Xem chi tiết chữ này →</button></>:<div className="empty-ink"><span>✎</span><p>{recognitionNote||'Hãy viết một ký tự để nhận diện.'}</p></div>}</div></div><p className="source-note">Nhận diện chữ: DaKanji / Dariyooo (DaAppLab), MIT.</p></section><section className="daily-card"><p className="eyebrow">GỢI Ý HÔM NAY</p><div className="ring"><b>10</b><span>phút</span></div><h2>Một bài học<br/>nhỏ, mỗi ngày</h2><p>Học 10 chữ Kanji N5 đầu tiên và tạo nền tảng thật vững chắc.</p><button className="primary">Bắt đầu học <span>→</span></button><div className="tiny-note">✦ Không cần tài khoản để bắt đầu</div></section></div>
<section className="library"><div className="section-heading"><div><p className="eyebrow">THƯ VIỆN KANJI</p><h2>Khám phá theo cấp độ</h2></div><button className="outline">Xem tất cả →</button></div><div className="levels">{['N5','N4','N3','N2','N1'].map((l,i)=><button className={i===0?'selected':''} key={l}><b>{l}</b><span>{[103,181,367,367,369][i]} chữ</span></button>)}</div><div className="kanji-grid">{KANJI.slice(0,8).map(k=><button key={k.char} onClick={()=>openKanji(k)}><b>{k.char}</b><span>{k.meaning.split(',')[0]}</span></button>)}</div></section></section>}

function Detail({item,back,notify}){return <section className="detail"><button className="back" onClick={back}>← Quay lại khám phá</button><div className="detail-hero"><div className="character-card">{item.char}<span>{item.kun.split('・')[0]}</span></div><div><p className="eyebrow">KANJI · JLPT {item.level}</p><h1>{item.meaning}</h1><div className="facts"><span>☷ {item.strokes} nét</span><span>◈ Bộ {item.radical}</span><span>◆ {item.level}</span></div><p className="memory">“Hãy liên tưởng chữ <b>{item.char}</b> với hình ảnh gần gũi để ghi nhớ thật lâu.”</p></div><button className="save" onClick={()=>notify(`Đã lưu chữ ${item.char} vào danh sách học`)}>♡ Lưu để học</button></div><div className="detail-layout"><section className="panel strokes"><div className="section-heading"><div><p className="eyebrow">THỨ TỰ NÉT</p><h2>Thứ tự viết {item.char}</h2></div><span className="word-count">{item.strokes} nét</span></div><StrokeOrder char={item.char}/><p className="hint">Số cạnh từng nét thể hiện đúng thứ tự viết.</p><p className="source-note">Nét viết: KanjiVG, CC BY-SA 3.0.</p></section><section className="panel readings"><p className="eyebrow">ÂM ĐỌC</p><h2>On & Kun</h2><dl><dt>Âm On</dt><dd>{item.on}</dd><dt>Âm Kun</dt><dd>{item.kun}</dd></dl><hr/><p className="eyebrow">BỘ THỦ</p><div className="radical"><b>{item.radical}</b><span>Bộ {item.radical} · thành phần chính của chữ</span></div></section></div><section className="panel words"><div className="section-heading"><div><p className="eyebrow">TỪ VỰNG LIÊN QUAN</p><h2>Học cùng ngữ cảnh</h2></div></div>{(item.words||[]).map(w=><div className="word" key={w}><b>{w.split('（')[0]}</b><span>{w.substring(w.indexOf('（'))}</span><button onClick={()=>notify('Đã thêm vào flashcard')}>＋</button></div>)}</section></section>}

function Learn({openKanji}){return <section className="simple-page"><p className="eyebrow">LỘ TRÌNH HỌC KANJI</p><h1>Đi từng bước nhỏ.</h1><p className="intro">Mỗi ngày 10 chữ, để chữ Kanji dần trở thành người bạn quen thuộc.</p><div className="course-grid">{['N5 · Nền tảng','N4 · Giao tiếp','N3 · Trung cấp'].map((x,i)=><article className={i?'course locked':'course'} key={x}><span>{i?'◌':'✦'}</span><p>JLPT</p><h2>{x}</h2><small>{[11,19,37][i]} ngày học · 10 chữ/ngày</small><button onClick={()=>i===0&&openKanji(KANJI[0])}>{i?'Sắp ra mắt':'Bắt đầu →'}</button></article>)}</div><div className="panel day-list"><p className="eyebrow">N5 · NGÀY 01</p><h2>Những chữ đầu tiên</h2>{KANJI.slice(0,5).map((k,i)=><button onClick={()=>openKanji(k)} key={k.char}><b>{String(i+1).padStart(2,'0')}</b><span className="small-char">{k.char}</span><span>{k.meaning}</span><i>→</i></button>)}</div></section>}

function Vocabulary({go}){
 const [groups,setGroups]=useState([]),[open,setOpen]=useState(1); useEffect(()=>{fetch('http://localhost:8010/lesson-groups?level=N5').then(r=>r.ok?r.json():[]).then(setGroups).catch(()=>setGroups([]))},[]);
 const lessons=groups.flatMap(group=>group.lessons), words=lessons.reduce((sum,lesson)=>sum+lesson.word_count,0);
 return <section className="vocabulary-index"><button className="back" onClick={()=>go('/')}>← Quay lại</button><h1>Từ vựng N5</h1><p>{groups.length} chủ đề · {lessons.length} bài nhỏ · {words} từ</p><section className="vocab-progress"><div><b>Tiến độ học</b><span>0/{lessons.length} bài</span></div><i/><small>0% hoàn thành</small></section><div className="vocab-groups">{groups.length?groups.map(group=><section className="vocab-group" key={group.id}><button className="group-toggle" onClick={()=>setOpen(open===group.id?null:group.id)} aria-expanded={open===group.id}><span className="group-japanese">{group.japanese_title}</span><strong>{group.title}</strong><small>{group.lessons.length} bài</small><i>{open===group.id?'⌄':'›'}</i></button>{open===group.id&&<div className="vocab-children">{group.lessons.map(lesson=><button onClick={()=>go(`/vocabulary/n5/lesson/${lesson.id}/flashcard`)} key={lesson.id}><b>▧</b><strong>Bài {lesson.order_index} · {lesson.title}</strong><span>{lesson.word_count} từ</span><i>›</i></button>)}</div>}</section>):<p>Đang tải bài học…</p>}</div><p className="source-note">Dữ liệu từ vựng: JMdict/EDICT (EDRDG), CC BY-SA 4.0.</p></section>}

function useLesson(id){const [lesson,setLesson]=useState(null);useEffect(()=>{fetch(`http://localhost:8010/lessons/${id}`).then(r=>r.ok?r.json():null).then(setLesson).catch(()=>setLesson(null))},[id]);return lesson}
function LessonDetail({lessonId,go}){const lesson=useLesson(lessonId);if(!lesson)return <section className="simple-page"><p>Đang tải bài học…</p></section>;return <section className="simple-page"><button className="back" onClick={()=>go('/vocabulary/n5')}>← Tất cả bài học</button><p className="eyebrow">JLPT {lesson.level} · BÀI {lesson.order_index}</p><h1>{lesson.title}</h1><p className="intro">{lesson.description}</p><section className="panel lesson-detail"><div className="section-heading"><div><p className="eyebrow">DANH SÁCH TỪ</p><h2>{lesson.vocabulary.length} từ vựng</h2></div><button className="primary" onClick={()=>go(`/vocabulary/n5/lesson/${lesson.id}/flashcard`)}>Bắt đầu flashcard →</button></div>{lesson.vocabulary.map((word,i)=><div className="word" key={word.id}><b>{String(i+1).padStart(2,'0')}</b><strong>{word.word}</strong><span>{word.reading} · {word.meaning}</span></div>)}</section></section>}
function Flashcards({lessonId,go}){const lesson=useLesson(lessonId),[index,setIndex]=useState(0),[flip,setFlip]=useState(false);useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);if(!lesson)return <section className="simple-page"><p>Đang tải flashcard…</p></section>;const words=lesson.vocabulary,word=words[index];if(!word)return <section className="simple-page"><p>Bài học này chưa có từ vựng.</p></section>;const next=()=>{setFlip(false);setIndex((index+1)%words.length)},prev=()=>{setFlip(false);setIndex((index-1+words.length)%words.length)},speak=(event)=>{event.stopPropagation();window.speechSynthesis?.cancel();const utterance=new SpeechSynthesisUtterance(word.word);utterance.lang='ja-JP';utterance.rate=.82;window.speechSynthesis?.speak(utterance)};return <section className="flashcard-page"><button className="back" onClick={()=>go('/vocabulary/n5')}>← Danh sách bài học</button><div className="flashcard-top"><div><p className="eyebrow">TỪ VỰNG N5 · BÀI {lesson.order_index}</p><h2>{lesson.title}</h2></div><span>{index+1} / {words.length}</span></div><div className="card-progress"><i style={{width:`${((index+1)/words.length)*100}%`}}/></div><div className={flip?'flashcard large flipped':'flashcard large'} role="button" tabIndex="0" onClick={()=>setFlip(!flip)} onKeyDown={e=>e.key==='Enter'&&setFlip(!flip)}><button className="card-nav previous" onClick={e=>{e.stopPropagation();prev()}} aria-label="Thẻ trước">‹</button>{flip?<><p>NGHĨA</p><h1>{word.meaning}</h1><small>Nhấp để xem mặt trước</small></>:<div className="flash-front"><p>TỪ VỰNG</p><h1>{word.word}</h1><b>{word.reading}</b><button className="speak" onClick={speak} aria-label="Phát âm tiếng Nhật">♬</button><FlashcardWritingPad expectedText={word.word}/><small>Nhấp vùng ngoài ô viết để lật thẻ</small></div>}<button className="card-nav next" onClick={e=>{e.stopPropagation();next()}} aria-label="Thẻ tiếp theo">›</button></div></section>}

function GrammarList({go}){const [lessons,setLessons]=useState([]);useEffect(()=>{fetch('http://localhost:8010/grammar/lessons?level=N5').then(r=>r.ok?r.json():[]).then(setLessons).catch(()=>setLessons([]))},[]);return <section className="simple-page vocabulary-page"><p className="eyebrow">JLPT N5 · NGỮ PHÁP</p><h1>Hiểu để dùng đúng.</h1><p className="intro">Năm bài đầu giới thiệu các mẫu câu căn bản, có công thức và ví dụ tự biên soạn.</p><div className="lesson-browser">{lessons.map((lesson,index)=><button key={lesson.id} onClick={()=>go(`/grammar/n5/lesson/${lesson.id}`)}><span>{String(index+1).padStart(2,'0')}</span><b>{lesson.title}</b><small>{lesson.description}</small><i>→</i></button>)}</div><p className="source-note">Nội dung ngữ pháp và ví dụ do KanjiAI tự biên soạn.</p></section>}
function GrammarLesson({lessonId,go}){const [lesson,setLesson]=useState(null);useEffect(()=>{fetch(`http://localhost:8010/grammar/lessons/${lessonId}`).then(r=>r.ok?r.json():null).then(setLesson).catch(()=>setLesson(null))},[lessonId]);if(!lesson)return <section className="simple-page"><p>Đang tải bài ngữ pháp…</p></section>;return <section className="grammar-detail"><button className="back" onClick={()=>go('/grammar/n5')}>← Ngữ pháp N5</button><header className="grammar-head"><div><p>第{lesson.order_index}課 · Bài {lesson.order_index}</p><h1>{lesson.title}</h1><small>{lesson.description}</small></div><button className="practice" disabled>✎ Bài tập (sắp có)</button></header>{lesson.patterns.map((pattern,index)=><section className="grammar-unit" key={pattern.id}><div className="pattern-heading"><span>MẪU {index+1}</span><h2>{pattern.formula}</h2></div><div className="grammar-cards"><article className="grammar-card structure"><p>⌁ CẤU TRÚC</p><code>{pattern.formula}</code></article><article className="grammar-card"><p>☷ GIẢI NGHĨA</p><b>{pattern.explanation_vi}</b><small>{lesson.description}</small></article><article className="grammar-card scope"><p>✺ PHẠM VI SỬ DỤNG</p><span>Dùng trong giao tiếp N5 cơ bản và tình huống lịch sự hằng ngày.</span></article><article className="grammar-card warning"><p>⚠ LƯU Ý</p><span>{pattern.note}</span></article></div><h3>Ví dụ</h3><div className="grammar-examples">{pattern.examples.map(example=><article key={example.id}><b>{example.japanese}</b><span>{example.reading}</span><small>{example.meaning_vi}</small></article>)}</div></section>)}</section>}

function Review({openKanji}){return <section className="simple-page"><p className="eyebrow">ÔN TẬP HÔM NAY</p><h1>Gặp lại đúng lúc.</h1><div className="review-tabs"><button className="active">Kanji <b>6</b></button><button>Từ vựng <b>12</b></button></div><section className="panel review-card"><div className="review-char">日</div><p>Hãy nhớ nghĩa và cách đọc của chữ này.</p><button className="primary" onClick={()=>openKanji(KANJI[0])}>Xem đáp án</button></section></section>}

function Settings({dark,setDark,notify}){return <section className="simple-page settings"><p className="eyebrow">CÀI ĐẶT</p><h1>Không gian học của bạn.</h1><section className="panel"><div className="setting"><div><b>Chế độ tối</b><small>Giảm mỏi mắt khi học buổi tối</small></div><button className={dark?'toggle on':'toggle'} onClick={()=>setDark(!dark)}><i/></button></div><div className="setting"><div><b>Hiệu ứng âm thanh</b><small>Âm thanh phản hồi khi học</small></div><button className="toggle" onClick={()=>notify('Đã cập nhật hiệu ứng âm thanh')}><i/></button></div><div className="setting"><div><b>Font Kanji</b><small>Chọn kiểu hiển thị chữ Hán</small></div><select defaultValue="Noto Serif JP"><option>Noto Serif JP</option><option>Yu Mincho</option><option>Hiragino Mincho</option></select></div></section></section>}
function Login({notify}){return <section className="login-page"><div className="login-card"><div className="logo big">漢</div><p className="eyebrow">CHÀO MỪNG TRỞ LẠI</p><h1>Tiếp tục hành trình.</h1><label>Email<input placeholder="you@example.com"/></label><label>Mật khẩu<input type="password" placeholder="••••••••"/></label><button className="primary wide" onClick={()=>notify('Đây là bản demo — đăng nhập sẽ sớm có')}>Đăng nhập</button><p>Chưa có tài khoản? <a>Đăng ký miễn phí</a></p></div></section>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
