import React, { useEffect, useRef, useState } from 'react';
import { BrowserRouter, useLocation, useNavigate } from 'react-router-dom';
import { createRoot } from 'react-dom/client';
import './styles.css';

let KANJI = [];
const nav = [['home','⌂','Trang chủ'],['learn','◈','Học Kanji'],['vocabulary','▤','Từ vựng'],['review','↻','Ôn tập']];
const KANJIVG_FILES = { '日':'065e5','人':'04eba','学':'05b66','食':'098df','水':'06c34','本':'0672c','会':'04f1a','山':'05c71','木':'06728','書':'066f8' };

function StrokeOrder({char}) {
  const host = useRef(null), [svg,setSvg] = useState(''), code = KANJIVG_FILES[char];
  useEffect(()=>{let active=true; setSvg(''); if(!code)return; fetch(`/kanjivg/${code}.svg`).then(r=>r.ok?r.text():Promise.reject()).then(markup=>active&&setSvg(markup.replace(/^<\?xml[\s\S]*?\?>/,'').replace(/<!--[\s\S]*?-->/g,'').replace(/<!DOCTYPE[\s\S]*?\]>\s*/,''))).catch(()=>active&&setSvg('')); return ()=>{active=false}},[code]);
  useEffect(()=>{if(!svg||!host.current)return; host.current.querySelectorAll('path').forEach(path=>{path.style.strokeDasharray='none';path.style.strokeDashoffset='0'});},[svg]);
  if(!code) return <div className="kanjivg-board fallback"><b>{char}</b><small>SVG nét viết đang được bổ sung</small></div>;
  return <div className="kanjivg-board" ref={host} aria-label={`Thứ tự nét chữ ${char}`}>{svg?<div dangerouslySetInnerHTML={{__html:svg}}/>:<span>Đang tải nét viết…</span>}</div>
}

function WritingCanvas({onRecognize}) {
  const canvasRef = useRef(null), isDrawing=useRef(false), timer=useRef();
  const [hasInk,setHasInk]=useState(false);
  const position=(e)=>{const r=canvasRef.current.getBoundingClientRect(); const p=e.touches?e.touches[0]:e; return {x:(p.clientX-r.left)*canvasRef.current.width/r.width,y:(p.clientY-r.top)*canvasRef.current.height/r.height}};
  useEffect(()=>{ const c=canvasRef.current, ctx=c.getContext('2d'); ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#d9d3c6';ctx.lineWidth=1;ctx.setLineDash([6,8]);ctx.beginPath();ctx.moveTo(200,0);ctx.lineTo(200,400);ctx.moveTo(0,200);ctx.lineTo(400,200);ctx.stroke(); },[]);
  const begin=(e)=>{e.preventDefault();isDrawing.current=true;const p=position(e),ctx=canvasRef.current.getContext('2d');ctx.setLineDash([]);ctx.strokeStyle='#1b2733';ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=14;ctx.beginPath();ctx.moveTo(p.x,p.y)};
  const draw=(e)=>{if(!isDrawing.current)return;e.preventDefault();const p=position(e);canvasRef.current.getContext('2d').lineTo(p.x,p.y);canvasRef.current.getContext('2d').stroke();setHasInk(true)};
  const end=()=>{if(!isDrawing.current)return;isDrawing.current=false;clearTimeout(timer.current);timer.current=setTimeout(()=>onRecognize(canvasRef.current.toDataURL('image/png')),650)};
  const clear=()=>{const c=canvasRef.current,ctx=c.getContext('2d');ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,400,400);ctx.strokeStyle='#d9d3c6';ctx.lineWidth=1;ctx.setLineDash([6,8]);ctx.beginPath();ctx.moveTo(200,0);ctx.lineTo(200,400);ctx.moveTo(0,200);ctx.stroke();setHasInk(false)};
  return <div className="canvas-wrap"><canvas ref={canvasRef} width="400" height="400" onMouseDown={begin} onMouseMove={draw} onMouseUp={end} onMouseLeave={end} onTouchStart={begin} onTouchMove={draw} onTouchEnd={end}/><button className="clear" onClick={clear} disabled={!hasInk}>↺ Xóa nét vẽ</button></div>
}

function App(){
 const [page,setPage]=useState('home'),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[results,setResults]=useState([]),[dark,setDark]=useState(false),[toast,setToast]=useState(''),[,setKanjiVersion]=useState(0);
 useEffect(()=>{fetch('http://localhost:8010/kanji?level=N5').then(r=>r.ok?r.json():[]).then(data=>{KANJI=data.map(x=>({...x,on:x.on_reading,kun:x.kun_reading,words:[]}));setKanjiVersion(v=>v+1)}).catch(()=>{KANJI=[];setKanjiVersion(v=>v+1)})},[]);
 const notify=(text)=>{setToast(text);setTimeout(()=>setToast(''),2400)};
 const recognition=async(img)=>{ setResults([]); try {let r=await fetch('http://localhost:8010/api/recognition',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:img})});let d=await r.json();setResults(d.predictions)}catch{setResults([{kanji:'食',confidence:.968},{kanji:'良',confidence:.014},{kanji:'会',confidence:.009}])} };
 const openKanji=(k)=>{setSelected(k);setPage('detail');window.scrollTo(0,0)};
 const matches=KANJI.filter(k=>`${k.char} ${k.meaning} ${k.on} ${k.kun}`.toLowerCase().includes(query.toLowerCase()));
 return <div className={dark?'app dark':'app'}>
  <aside><div className="brand"><div className="logo">漢</div><div><b>Kanji<span>AI</span></b><small>Học chữ Nhật mỗi ngày</small></div></div><nav>{nav.map(([id,ic,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><i>{ic}</i>{label}</button>)}</nav><div className="sidebar-bottom"><button onClick={()=>setPage('settings')}><i>⚙</i>Cài đặt</button><button onClick={()=>setPage('login')}><i>◉</i>Đăng nhập</button></div></aside>
  <main><header><div className="crumb">{page==='home'?'Khám phá':page==='detail'?'Kanji / '+selected?.char:'Học tiếng Nhật'}</div><div className="head-actions"><button className="theme" onClick={()=>setDark(!dark)}>{dark?'☀':'☾'}</button><div className="avatar">H</div></div></header>
  {page==='home'&&<Home query={query} setQuery={setQuery} matches={matches} openKanji={openKanji} results={results} recognition={recognition}/>} 
  {page==='detail'&&<Detail item={selected||KANJI[0]} back={()=>setPage('home')} notify={notify}/>} 
  {page==='learn'&&<Learn openKanji={openKanji}/>} {page==='vocabulary'&&<Vocabulary notify={notify}/>} {page==='review'&&<Review openKanji={openKanji}/>} {page==='settings'&&<Settings dark={dark} setDark={setDark} notify={notify}/>} {page==='login'&&<Login notify={notify}/>} 
  </main>{toast&&<div className="toast">✓ {toast}</div>}</div>
}

function Home({query,setQuery,matches,openKanji,results,recognition}){return <section className="home"><div className="hero"><div><p className="eyebrow">KANJI AI · BẮT ĐẦU HÔM NAY</p><h1>Viết một nét,<br/><em>nhớ một đời.</em></h1><p className="intro">Khám phá Kanji theo cách trực quan hơn — tra cứu, luyện viết và học mỗi ngày.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm Kanji, âm Hán Việt hoặc ý nghĩa..."/>{query&&<div className="suggestions">{matches.map(k=><button key={k.char} onClick={()=>openKanji(k)}><b>{k.char}</b><span>{k.meaning}</span></button>)||<p>Không tìm thấy kết quả</p>}</div>}</div></div><div className="hero-mark">学<small>まなぶ</small></div></div>
<div className="two-col"><section className="panel writing"><div className="panel-title"><div><p className="eyebrow">AI HANDWRITING</p><h2>Viết Kanji để tra cứu</h2></div><span className="live"><i/> AI sẵn sàng</span></div><p className="hint">Viết chữ vào ô bên dưới. AI sẽ tự nhận diện khi bạn dừng bút.</p><div className="write-grid"><WritingCanvas onRecognize={recognition}/><div className="prediction"><p className="prediction-label">{results.length?'KẾT QUẢ NHẬN DIỆN':'ĐANG CHỜ NÉT VIẾT'}</p>{results.length?<>{results.map((r,i)=><div className="pred" key={r.kanji}><b>{r.kanji}</b><div><div className="bar"><i style={{width:`${r.confidence*100}%`}}/></div><small>Độ tin cậy {Math.round(r.confidence*100)}%</small></div>{i===0&&<span>Khả năng cao</span>}</div>)}<button className="link-button" onClick={()=>openKanji(KANJI.find(k=>k.char===results[0].kanji)||KANJI[3])}>Xem chi tiết chữ này →</button></>:<div className="empty-ink"><span>✎</span><p>Nét bút của bạn sẽ xuất hiện ở đây</p></div>}</div></div></section><section className="daily-card"><p className="eyebrow">GỢI Ý HÔM NAY</p><div className="ring"><b>10</b><span>phút</span></div><h2>Một bài học<br/>nhỏ, mỗi ngày</h2><p>Học 10 chữ Kanji N5 đầu tiên và tạo nền tảng thật vững chắc.</p><button className="primary">Bắt đầu học <span>→</span></button><div className="tiny-note">✦ Không cần tài khoản để bắt đầu</div></section></div>
<section className="library"><div className="section-heading"><div><p className="eyebrow">THƯ VIỆN KANJI</p><h2>Khám phá theo cấp độ</h2></div><button className="outline">Xem tất cả →</button></div><div className="levels">{['N5','N4','N3','N2','N1'].map((l,i)=><button className={i===0?'selected':''} key={l}><b>{l}</b><span>{[103,181,367,367,369][i]} chữ</span></button>)}</div><div className="kanji-grid">{KANJI.slice(0,8).map(k=><button key={k.char} onClick={()=>openKanji(k)}><b>{k.char}</b><span>{k.meaning.split(',')[0]}</span></button>)}</div></section></section>}

function Detail({item,back,notify}){return <section className="detail"><button className="back" onClick={back}>← Quay lại khám phá</button><div className="detail-hero"><div className="character-card">{item.char}<span>{item.kun.split('・')[0]}</span></div><div><p className="eyebrow">KANJI · JLPT {item.level}</p><h1>{item.meaning}</h1><div className="facts"><span>☷ {item.strokes} nét</span><span>◈ Bộ {item.radical}</span><span>◆ {item.level}</span></div><p className="memory">“Hãy liên tưởng chữ <b>{item.char}</b> với hình ảnh gần gũi để ghi nhớ thật lâu.”</p></div><button className="save" onClick={()=>notify(`Đã lưu chữ ${item.char} vào danh sách học`)}>♡ Lưu để học</button></div><div className="detail-layout"><section className="panel strokes"><div className="section-heading"><div><p className="eyebrow">THỨ TỰ NÉT</p><h2>Thứ tự viết {item.char}</h2></div><span className="word-count">{item.strokes} nét</span></div><StrokeOrder char={item.char}/><p className="hint">Số cạnh từng nét thể hiện đúng thứ tự viết.</p><p className="source-note">Nét viết: KanjiVG, CC BY-SA 3.0.</p></section><section className="panel readings"><p className="eyebrow">ÂM ĐỌC</p><h2>On & Kun</h2><dl><dt>Âm On</dt><dd>{item.on}</dd><dt>Âm Kun</dt><dd>{item.kun}</dd></dl><hr/><p className="eyebrow">BỘ THỦ</p><div className="radical"><b>{item.radical}</b><span>Bộ {item.radical} · thành phần chính của chữ</span></div></section></div><section className="panel words"><div className="section-heading"><div><p className="eyebrow">TỪ VỰNG LIÊN QUAN</p><h2>Học cùng ngữ cảnh</h2></div></div>{(item.words||[]).map(w=><div className="word" key={w}><b>{w.split('（')[0]}</b><span>{w.substring(w.indexOf('（'))}</span><button onClick={()=>notify('Đã thêm vào flashcard')}>＋</button></div>)}</section></section>}

function Learn({openKanji}){return <section className="simple-page"><p className="eyebrow">LỘ TRÌNH HỌC KANJI</p><h1>Đi từng bước nhỏ.</h1><p className="intro">Mỗi ngày 10 chữ, để chữ Kanji dần trở thành người bạn quen thuộc.</p><div className="course-grid">{['N5 · Nền tảng','N4 · Giao tiếp','N3 · Trung cấp'].map((x,i)=><article className={i?'course locked':'course'} key={x}><span>{i?'◌':'✦'}</span><p>JLPT</p><h2>{x}</h2><small>{[11,19,37][i]} ngày học · 10 chữ/ngày</small><button onClick={()=>i===0&&openKanji(KANJI[0])}>{i?'Sắp ra mắt':'Bắt đầu →'}</button></article>)}</div><div className="panel day-list"><p className="eyebrow">N5 · NGÀY 01</p><h2>Những chữ đầu tiên</h2>{KANJI.slice(0,5).map((k,i)=><button onClick={()=>openKanji(k)} key={k.char}><b>{String(i+1).padStart(2,'0')}</b><span className="small-char">{k.char}</span><span>{k.meaning}</span><i>→</i></button>)}</div></section>}

function Vocabulary({notify}){
 const [flip,setFlip]=useState(false),[lessons,setLessons]=useState([]),[lesson,setLesson]=useState(null),[words,setWords]=useState([]),[card,setCard]=useState(0);
 useEffect(()=>{fetch('http://localhost:8010/lessons?level=N5').then(r=>r.ok?r.json():[]).then(data=>{setLessons(data);if(data[0])setLesson(data[0].id)}).catch(()=>setLessons([]))},[]);
 useEffect(()=>{if(!lesson)return;setFlip(false);setCard(0);fetch(`http://localhost:8010/lessons/${lesson}`).then(r=>r.json()).then(data=>setWords(data.vocabulary||[])).catch(()=>setWords([]))},[lesson]);
 const word=words[card]||{word:'食べる',reading:'たべる',meaning:'Ăn · bữa ăn'};
 return <section className="simple-page vocabulary-page"><p className="eyebrow">JLPT N5 · TỪ VỰNG CƠ BẢN</p><h1>Học theo từng chủ đề.</h1><p className="intro">Lộ trình N5 gồm các bài học nhỏ, mỗi bài tập trung vào những từ thiết yếu để dùng ngay.</p><div className="lesson-browser">{lessons.length?lessons.map((x,i)=><button className={lesson===x.id?'active':''} onClick={()=>setLesson(x.id)} key={x.id}><span>{String(i+1).padStart(2,'0')}</span><b>{x.title}</b><small>{x.description}</small><i>→</i></button>):<p>Đang tải bài học…</p>}</div><div className="study-section"><div><p className="eyebrow">FLASHCARD</p><h2>{lessons.find(x=>x.id===lesson)?.title||'Bài học'}</h2></div><span className="word-count">{words.length||0} từ</span></div><div className="flashcard" onClick={()=>setFlip(!flip)}>{flip?<><p>NGHĨA</p><h2>{word.meaning}</h2><small>Nhấp để xem lại mặt trước</small></>:<><p>FLASHCARD {String(card+1).padStart(2,'0')} / {words.length||1}</p><h1>{word.word}</h1><b>{word.reading}</b><small>Nhấp để lật thẻ</small></>}</div><div className="flash-actions"><button onClick={()=>notify('Đã đánh dấu: Cần ôn lại')}>Chưa nhớ</button><button className="primary" onClick={()=>{setFlip(false);setCard((card+1)%Math.max(words.length,1));notify('Đã chuyển sang thẻ tiếp theo')}}>Đã nhớ ✓</button></div><p className="source-note">Dữ liệu từ vựng: JMdict/EDICT (EDRDG), CC BY-SA 4.0.</p></section>}

function Review({openKanji}){return <section className="simple-page"><p className="eyebrow">ÔN TẬP HÔM NAY</p><h1>Gặp lại đúng lúc.</h1><div className="review-tabs"><button className="active">Kanji <b>6</b></button><button>Từ vựng <b>12</b></button></div><section className="panel review-card"><div className="review-char">日</div><p>Hãy nhớ nghĩa và cách đọc của chữ này.</p><button className="primary" onClick={()=>openKanji(KANJI[0])}>Xem đáp án</button></section></section>}

function Settings({dark,setDark,notify}){return <section className="simple-page settings"><p className="eyebrow">CÀI ĐẶT</p><h1>Không gian học của bạn.</h1><section className="panel"><div className="setting"><div><b>Chế độ tối</b><small>Giảm mỏi mắt khi học buổi tối</small></div><button className={dark?'toggle on':'toggle'} onClick={()=>setDark(!dark)}><i/></button></div><div className="setting"><div><b>Hiệu ứng âm thanh</b><small>Âm thanh phản hồi khi học</small></div><button className="toggle" onClick={()=>notify('Đã cập nhật hiệu ứng âm thanh')}><i/></button></div><div className="setting"><div><b>Font Kanji</b><small>Chọn kiểu hiển thị chữ Hán</small></div><select defaultValue="Noto Serif JP"><option>Noto Serif JP</option><option>Yu Mincho</option><option>Hiragino Mincho</option></select></div></section></section>}
function Login({notify}){return <section className="login-page"><div className="login-card"><div className="logo big">漢</div><p className="eyebrow">CHÀO MỪNG TRỞ LẠI</p><h1>Tiếp tục hành trình.</h1><label>Email<input placeholder="you@example.com"/></label><label>Mật khẩu<input type="password" placeholder="••••••••"/></label><button className="primary wide" onClick={()=>notify('Đây là bản demo — đăng nhập sẽ sớm có')}>Đăng nhập</button><p>Chưa có tài khoản? <a>Đăng ký miễn phí</a></p></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
